; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -O3 -S -mtriple=x86_64-- -mcpu=x86-64-v3 < %s | FileCheck %s

; End-to-end checks for the compare->bitmask ("movemask") pack idiom
; (llvm/llvm-project#121691):
;
;   for (b = 0; b < 8; ++b)
;     word |= (uint8_t)(p[b] != 0) << b;
;
; The idiom reaches the optimizer in two distinct shapes:
;  * @pack8: the scalar (pre-unrolled) chain. The SLP vectorizer recognizes
;    the whole reduction and emits `bitcast <8 x i1> to i8` directly
;    (llvm/llvm-project#181940).
;  * @pack8_vector_ir / @pack8_vector_ir_shl: already-vectorized IR (e.g. from
;    portable SIMD libraries or C vector extensions). SLP never sees this, so
;    InstCombine folds the weighted reduction to the same bitcast.

define i8 @pack8(ptr %p) {
; CHECK-LABEL: @pack8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i8>, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[TMP0]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    ret i8 [[TMP2]]
;
entry:
  %g1 = getelementptr i8, ptr %p, i64 1
  %g2 = getelementptr i8, ptr %p, i64 2
  %g3 = getelementptr i8, ptr %p, i64 3
  %g4 = getelementptr i8, ptr %p, i64 4
  %g5 = getelementptr i8, ptr %p, i64 5
  %g6 = getelementptr i8, ptr %p, i64 6
  %g7 = getelementptr i8, ptr %p, i64 7
  %v0 = load i8, ptr %p
  %v1 = load i8, ptr %g1
  %v2 = load i8, ptr %g2
  %v3 = load i8, ptr %g3
  %v4 = load i8, ptr %g4
  %v5 = load i8, ptr %g5
  %v6 = load i8, ptr %g6
  %v7 = load i8, ptr %g7
  %c0 = icmp ne i8 %v0, 0
  %c1 = icmp ne i8 %v1, 0
  %c2 = icmp ne i8 %v2, 0
  %c3 = icmp ne i8 %v3, 0
  %c4 = icmp ne i8 %v4, 0
  %c5 = icmp ne i8 %v5, 0
  %c6 = icmp ne i8 %v6, 0
  %c7 = icmp ne i8 %v7, 0
  %z0 = zext i1 %c0 to i8
  %z1 = zext i1 %c1 to i8
  %z2 = zext i1 %c2 to i8
  %z3 = zext i1 %c3 to i8
  %z4 = zext i1 %c4 to i8
  %z5 = zext i1 %c5 to i8
  %z6 = zext i1 %c6 to i8
  %z7 = zext i1 %c7 to i8
  %s1 = shl i8 %z1, 1
  %s2 = shl i8 %z2, 2
  %s3 = shl i8 %z3, 3
  %s4 = shl i8 %z4, 4
  %s5 = shl i8 %z5, 5
  %s6 = shl i8 %z6, 6
  %s7 = shl i8 %z7, 7
  %o0 = or i8 %z0, %s1
  %o1 = or i8 %o0, %s2
  %o2 = or i8 %o1, %s3
  %o3 = or i8 %o2, %s4
  %o4 = or i8 %o3, %s5
  %o5 = or i8 %o4, %s6
  %o6 = or i8 %o5, %s7
  ret i8 %o6
}

define i8 @pack8_vector_ir(<8 x i1> %m) {
; CHECK-LABEL: @pack8_vector_ir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = tail call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
entry:
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

define i8 @pack8_vector_ir_shl(<8 x i1> %m) {
; CHECK-LABEL: @pack8_vector_ir_shl(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = tail call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SHL]])
; CHECK-NEXT:    ret i8 [[R]]
;
entry:
  %z = zext <8 x i1> %m to <8 x i8>
  %shl = shl <8 x i8> %z, <i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %shl)
  ret i8 %r
}
