; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -O3 -S -mtriple=x86_64-- -mcpu=x86-64-v3 < %s | FileCheck %s

; End-to-end checks for the compare->bitmask ("movemask") pack idiom
; (llvm/llvm-project#121691):
;
;   for (b = 0; b < 8; ++b)
;     word |= (uint8_t)(p[b] != 0) << b;
;
; The idiom reaches the optimizer in two distinct shapes:
;  * @pack8: the scalar (pre-unrolled) chain. The SLP vectorizer recognizes
;    the whole reduction and emits `bitcast <8 x i1> to i8` directly
;    (llvm/llvm-project#181940).
;  * @pack8_vector_ir / @pack8_vector_ir_shl: already-vectorized IR (e.g. from
;    portable SIMD libraries or C vector extensions). SLP never sees this, so
;    InstCombine folds the weighted reduction to the same bitcast.

define i8 @pack8(ptr %p) {
; CHECK-LABEL: @pack8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i8>, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[TMP0]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    ret i8 [[TMP2]]
;
entry:
  %g1 = getelementptr i8, ptr %p, i64 1
  %g2 = getelementptr i8, ptr %p, i64 2
  %g3 = getelementptr i8, ptr %p, i64 3
  %g4 = getelementptr i8, ptr %p, i64 4
  %g5 = getelementptr i8, ptr %p, i64 5
  %g6 = getelementptr i8, ptr %p, i64 6
  %g7 = getelementptr i8, ptr %p, i64 7
  %v0 = load i8, ptr %p
  %v1 = load i8, ptr %g1
  %v2 = load i8, ptr %g2
  %v3 = load i8, ptr %g3
  %v4 = load i8, ptr %g4
  %v5 = load i8, ptr %g5
  %v6 = load i8, ptr %g6
  %v7 = load i8, ptr %g7
  %c0 = icmp ne i8 %v0, 0
  %c1 = icmp ne i8 %v1, 0
  %c2 = icmp ne i8 %v2, 0
  %c3 = icmp ne i8 %v3, 0
  %c4 = icmp ne i8 %v4, 0
  %c5 = icmp ne i8 %v5, 0
  %c6 = icmp ne i8 %v6, 0
  %c7 = icmp ne i8 %v7, 0
  %z0 = zext i1 %c0 to i8
  %z1 = zext i1 %c1 to i8
  %z2 = zext i1 %c2 to i8
  %z3 = zext i1 %c3 to i8
  %z4 = zext i1 %c4 to i8
  %z5 = zext i1 %c5 to i8
  %z6 = zext i1 %c6 to i8
  %z7 = zext i1 %c7 to i8
  %s1 = shl i8 %z1, 1
  %s2 = shl i8 %z2, 2
  %s3 = shl i8 %z3, 3
  %s4 = shl i8 %z4, 4
  %s5 = shl i8 %z5, 5
  %s6 = shl i8 %z6, 6
  %s7 = shl i8 %z7, 7
  %o0 = or i8 %z0, %s1
  %o1 = or i8 %o0, %s2
  %o2 = or i8 %o1, %s3
  %o3 = or i8 %o2, %s4
  %o4 = or i8 %o3, %s5
  %o5 = or i8 %o4, %s6
  %o6 = or i8 %o5, %s7
  ret i8 %o6
}

define i8 @pack8_vector_ir(<8 x i1> %m) {
; CHECK-LABEL: @pack8_vector_ir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
entry:
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

define i8 @pack8_vector_ir_shl(<8 x i1> %m) {
; CHECK-LABEL: @pack8_vector_ir_shl(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
entry:
  %z = zext <8 x i1> %m to <8 x i8>
  %shl = shl <8 x i8> %z, <i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %shl)
  ret i8 %r
}

; Compare-fed vector IR: InstCombine swaps the select arms (icmp ne -> eq)
; before the reduce fold runs, so the inverted-arm form must also be matched.
define i8 @pack8_vector_ir_cmp(ptr %p) {
; CHECK-LABEL: @pack8_vector_ir_cmp(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[V:%.*]] = load <8 x i8>, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[M_NOT:%.*]] = icmp ne <8 x i8> [[V]], zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M_NOT]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
entry:
  %v = load <8 x i8>, ptr %p, align 1
  %m = icmp ne <8 x i8> %v, zeroinitializer
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; The arrow-rs MutableBuffer::collect_bool pattern: an outer loop packing 64
; (data[i] != 0) bits per u64 word. LoopVectorize claims the inner pack loop
; (VF=4, IC=4); when the resulting vector loop fully unrolls (as here), the
; reduction becomes an or-tree of constant bit-position weighted selects with
; INVERTED arms -- a chunked variant of the movemask idiom that the
; single-ramp reduce fold cannot match. When surrounding code blocks the
; unroll (e.g. the real arrow-rs version pushing to a Vec), the loop is kept
; and the shifts are induction-variable vectors instead.
; TODO: fold the chunked constant form to per-chunk bitcasts + shift + or;
; the loop-carried form needs a LoopVectorize/VPlan bit-pack reduction.
define void @collect_bool_pack_loop(ptr %data, i64 %chunks, ptr %out) {
; CHECK-LABEL: define void @collect_bool_pack_loop(
; CHECK-SAME: ptr nofree readonly captures(none) [[DATA:%.*]], i64 [[CHUNKS:%.*]], ptr nofree writeonly captures(none) [[OUT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[EMPTY:%.*]] = icmp eq i64 [[CHUNKS]], 0
; CHECK-NEXT:    br i1 [[EMPTY]], label %[[EXIT:.*]], label %[[OUTER:.*]]
; CHECK:       [[OUTER]]:
; CHECK-NEXT:    [[CHUNK:%.*]] = phi i64 [ [[CHUNK_NEXT:%.*]], %[[OUTER]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[BASE:%.*]] = shl i64 [[CHUNK]], 6
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[DATA]], i64 [[BASE]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP0]], i64 12
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[WIDE_LOAD4:%.*]] = load <4 x i8>, ptr [[TMP1]], align 1
; CHECK-NEXT:    [[WIDE_LOAD5:%.*]] = load <4 x i8>, ptr [[TMP2]], align 1
; CHECK-NEXT:    [[WIDE_LOAD6:%.*]] = load <4 x i8>, ptr [[TMP3]], align 1
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT14:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD4]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT15:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD5]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT16:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD6]], zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = select <4 x i1> [[DOTNOT]], <4 x i64> zeroinitializer, <4 x i64> <i64 1, i64 2, i64 4, i64 8>
; CHECK-NEXT:    [[TMP5:%.*]] = select <4 x i1> [[DOTNOT14]], <4 x i64> zeroinitializer, <4 x i64> <i64 16, i64 32, i64 64, i64 128>
; CHECK-NEXT:    [[TMP6:%.*]] = select <4 x i1> [[DOTNOT15]], <4 x i64> zeroinitializer, <4 x i64> <i64 256, i64 512, i64 1024, i64 2048>
; CHECK-NEXT:    [[TMP7:%.*]] = select <4 x i1> [[DOTNOT16]], <4 x i64> zeroinitializer, <4 x i64> <i64 4096, i64 8192, i64 16384, i64 32768>
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP0]], i64 16
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[TMP0]], i64 20
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[TMP0]], i64 24
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP0]], i64 28
; CHECK-NEXT:    [[WIDE_LOAD_1:%.*]] = load <4 x i8>, ptr [[TMP8]], align 1
; CHECK-NEXT:    [[WIDE_LOAD4_1:%.*]] = load <4 x i8>, ptr [[TMP9]], align 1
; CHECK-NEXT:    [[WIDE_LOAD5_1:%.*]] = load <4 x i8>, ptr [[TMP10]], align 1
; CHECK-NEXT:    [[WIDE_LOAD6_1:%.*]] = load <4 x i8>, ptr [[TMP11]], align 1
; CHECK-NEXT:    [[DOTNOT17:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD_1]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT18:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD4_1]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT19:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD5_1]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT20:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD6_1]], zeroinitializer
; CHECK-NEXT:    [[TMP12:%.*]] = select <4 x i1> [[DOTNOT17]], <4 x i64> zeroinitializer, <4 x i64> <i64 65536, i64 131072, i64 262144, i64 524288>
; CHECK-NEXT:    [[TMP13:%.*]] = select <4 x i1> [[DOTNOT18]], <4 x i64> zeroinitializer, <4 x i64> <i64 1048576, i64 2097152, i64 4194304, i64 8388608>
; CHECK-NEXT:    [[TMP14:%.*]] = select <4 x i1> [[DOTNOT19]], <4 x i64> zeroinitializer, <4 x i64> <i64 16777216, i64 33554432, i64 67108864, i64 134217728>
; CHECK-NEXT:    [[TMP15:%.*]] = select <4 x i1> [[DOTNOT20]], <4 x i64> zeroinitializer, <4 x i64> <i64 268435456, i64 536870912, i64 1073741824, i64 2147483648>
; CHECK-NEXT:    [[TMP16:%.*]] = or disjoint <4 x i64> [[TMP12]], [[TMP4]]
; CHECK-NEXT:    [[TMP17:%.*]] = or disjoint <4 x i64> [[TMP13]], [[TMP5]]
; CHECK-NEXT:    [[TMP18:%.*]] = or disjoint <4 x i64> [[TMP14]], [[TMP6]]
; CHECK-NEXT:    [[TMP19:%.*]] = or disjoint <4 x i64> [[TMP15]], [[TMP7]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[TMP0]], i64 32
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr i8, ptr [[TMP0]], i64 36
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr i8, ptr [[TMP0]], i64 40
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr i8, ptr [[TMP0]], i64 44
; CHECK-NEXT:    [[WIDE_LOAD_2:%.*]] = load <4 x i8>, ptr [[TMP20]], align 1
; CHECK-NEXT:    [[WIDE_LOAD4_2:%.*]] = load <4 x i8>, ptr [[TMP21]], align 1
; CHECK-NEXT:    [[WIDE_LOAD5_2:%.*]] = load <4 x i8>, ptr [[TMP22]], align 1
; CHECK-NEXT:    [[WIDE_LOAD6_2:%.*]] = load <4 x i8>, ptr [[TMP23]], align 1
; CHECK-NEXT:    [[DOTNOT21:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD_2]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT22:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD4_2]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT23:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD5_2]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT24:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD6_2]], zeroinitializer
; CHECK-NEXT:    [[TMP24:%.*]] = select <4 x i1> [[DOTNOT21]], <4 x i64> zeroinitializer, <4 x i64> <i64 4294967296, i64 8589934592, i64 17179869184, i64 34359738368>
; CHECK-NEXT:    [[TMP25:%.*]] = select <4 x i1> [[DOTNOT22]], <4 x i64> zeroinitializer, <4 x i64> <i64 68719476736, i64 137438953472, i64 274877906944, i64 549755813888>
; CHECK-NEXT:    [[TMP26:%.*]] = select <4 x i1> [[DOTNOT23]], <4 x i64> zeroinitializer, <4 x i64> <i64 1099511627776, i64 2199023255552, i64 4398046511104, i64 8796093022208>
; CHECK-NEXT:    [[TMP27:%.*]] = select <4 x i1> [[DOTNOT24]], <4 x i64> zeroinitializer, <4 x i64> <i64 17592186044416, i64 35184372088832, i64 70368744177664, i64 140737488355328>
; CHECK-NEXT:    [[TMP28:%.*]] = or disjoint <4 x i64> [[TMP24]], [[TMP16]]
; CHECK-NEXT:    [[TMP29:%.*]] = or disjoint <4 x i64> [[TMP25]], [[TMP17]]
; CHECK-NEXT:    [[TMP30:%.*]] = or disjoint <4 x i64> [[TMP26]], [[TMP18]]
; CHECK-NEXT:    [[TMP31:%.*]] = or disjoint <4 x i64> [[TMP27]], [[TMP19]]
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[TMP0]], i64 48
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i8, ptr [[TMP0]], i64 52
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr i8, ptr [[TMP0]], i64 56
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[TMP0]], i64 60
; CHECK-NEXT:    [[WIDE_LOAD_3:%.*]] = load <4 x i8>, ptr [[TMP32]], align 1
; CHECK-NEXT:    [[WIDE_LOAD4_3:%.*]] = load <4 x i8>, ptr [[TMP33]], align 1
; CHECK-NEXT:    [[WIDE_LOAD5_3:%.*]] = load <4 x i8>, ptr [[TMP34]], align 1
; CHECK-NEXT:    [[WIDE_LOAD6_3:%.*]] = load <4 x i8>, ptr [[TMP35]], align 1
; CHECK-NEXT:    [[DOTNOT25:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD_3]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT26:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD4_3]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT27:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD5_3]], zeroinitializer
; CHECK-NEXT:    [[DOTNOT28:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD6_3]], zeroinitializer
; CHECK-NEXT:    [[TMP36:%.*]] = select <4 x i1> [[DOTNOT25]], <4 x i64> zeroinitializer, <4 x i64> <i64 281474976710656, i64 562949953421312, i64 1125899906842624, i64 2251799813685248>
; CHECK-NEXT:    [[TMP37:%.*]] = select <4 x i1> [[DOTNOT26]], <4 x i64> zeroinitializer, <4 x i64> <i64 4503599627370496, i64 9007199254740992, i64 18014398509481984, i64 36028797018963968>
; CHECK-NEXT:    [[TMP38:%.*]] = select <4 x i1> [[DOTNOT27]], <4 x i64> zeroinitializer, <4 x i64> <i64 72057594037927936, i64 144115188075855872, i64 288230376151711744, i64 576460752303423488>
; CHECK-NEXT:    [[TMP39:%.*]] = select <4 x i1> [[DOTNOT28]], <4 x i64> zeroinitializer, <4 x i64> <i64 1152921504606846976, i64 2305843009213693952, i64 4611686018427387904, i64 -9223372036854775808>
; CHECK-NEXT:    [[TMP40:%.*]] = or disjoint <4 x i64> [[TMP36]], [[TMP28]]
; CHECK-NEXT:    [[TMP41:%.*]] = or disjoint <4 x i64> [[TMP37]], [[TMP29]]
; CHECK-NEXT:    [[TMP42:%.*]] = or disjoint <4 x i64> [[TMP38]], [[TMP30]]
; CHECK-NEXT:    [[TMP43:%.*]] = or disjoint <4 x i64> [[TMP39]], [[TMP31]]
; CHECK-NEXT:    [[BIN_RDX:%.*]] = or disjoint <4 x i64> [[TMP41]], [[TMP40]]
; CHECK-NEXT:    [[BIN_RDX7:%.*]] = or disjoint <4 x i64> [[TMP42]], [[BIN_RDX]]
; CHECK-NEXT:    [[BIN_RDX8:%.*]] = or <4 x i64> [[TMP43]], [[BIN_RDX7]]
; CHECK-NEXT:    [[TMP44:%.*]] = tail call i64 @llvm.vector.reduce.or.v4i64(<4 x i64> [[BIN_RDX8]])
; CHECK-NEXT:    [[OG:%.*]] = getelementptr [8 x i8], ptr [[OUT]], i64 [[CHUNK]]
; CHECK-NEXT:    store i64 [[TMP44]], ptr [[OG]], align 8
; CHECK-NEXT:    [[CHUNK_NEXT]] = add nuw i64 [[CHUNK]], 1
; CHECK-NEXT:    [[OUTER_DONE:%.*]] = icmp eq i64 [[CHUNK_NEXT]], [[CHUNKS]]
; CHECK-NEXT:    br i1 [[OUTER_DONE]], label %[[EXIT]], label %[[OUTER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %empty = icmp eq i64 %chunks, 0
  br i1 %empty, label %exit, label %outer

outer:
  %chunk = phi i64 [ %chunk.next, %latch ], [ 0, %entry ]
  %base = shl i64 %chunk, 6
  br label %inner

inner:
  %bit = phi i64 [ 0, %outer ], [ %bit.next, %inner ]
  %packed = phi i64 [ 0, %outer ], [ %packed.next, %inner ]
  %i = add i64 %base, %bit
  %g = getelementptr i8, ptr %data, i64 %i
  %v = load i8, ptr %g, align 1
  %c = icmp ne i8 %v, 0
  %z = zext i1 %c to i64
  %s = shl i64 %z, %bit
  %packed.next = or i64 %packed, %s
  %bit.next = add nuw nsw i64 %bit, 1
  %done = icmp eq i64 %bit.next, 64
  br i1 %done, label %latch, label %inner

latch:
  %og = getelementptr i64, ptr %out, i64 %chunk
  store i64 %packed.next, ptr %og, align 8
  %chunk.next = add nuw i64 %chunk, 1
  %outer.done = icmp eq i64 %chunk.next, %chunks
  br i1 %outer.done, label %exit, label %outer

exit:
  ret void
}
