; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=slp-vectorizer -mtriple=aarch64-unknown-linux-gnu -S < %s | FileCheck %s

; A multi-column comparator emitting one -1/0/1 byte per 128-bit key. The
; ucmp operands are i128, so vectorising them into <8 x i8> ucmp of <8 x i128>
; is scalarised again by the backend and is not profitable.

define void @ucmp_i128_columns(ptr %dst, ptr %x, ptr %y) {
; CHECK-LABEL: define void @ucmp_i128_columns(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[X:%.*]], ptr [[Y:%.*]]) {
; CHECK-NEXT:    [[A_0:%.*]] = load i128, ptr [[X]], align 16
; CHECK-NEXT:    [[B_0:%.*]] = load i128, ptr [[Y]], align 16
; CHECK-NEXT:    [[C_0:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_0]], i128 [[B_0]])
; CHECK-NEXT:    store i8 [[C_0]], ptr [[DST]], align 1
; CHECK-NEXT:    [[X_1:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 16
; CHECK-NEXT:    [[Y_1:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 16
; CHECK-NEXT:    [[DST_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 1
; CHECK-NEXT:    [[A_1:%.*]] = load i128, ptr [[X_1]], align 16
; CHECK-NEXT:    [[B_1:%.*]] = load i128, ptr [[Y_1]], align 16
; CHECK-NEXT:    [[C_1:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_1]], i128 [[B_1]])
; CHECK-NEXT:    store i8 [[C_1]], ptr [[DST_1]], align 1
; CHECK-NEXT:    [[X_2:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 32
; CHECK-NEXT:    [[Y_2:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 32
; CHECK-NEXT:    [[DST_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 2
; CHECK-NEXT:    [[A_2:%.*]] = load i128, ptr [[X_2]], align 16
; CHECK-NEXT:    [[B_2:%.*]] = load i128, ptr [[Y_2]], align 16
; CHECK-NEXT:    [[C_2:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_2]], i128 [[B_2]])
; CHECK-NEXT:    store i8 [[C_2]], ptr [[DST_2]], align 1
; CHECK-NEXT:    [[X_3:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 48
; CHECK-NEXT:    [[Y_3:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 48
; CHECK-NEXT:    [[DST_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 3
; CHECK-NEXT:    [[A_3:%.*]] = load i128, ptr [[X_3]], align 16
; CHECK-NEXT:    [[B_3:%.*]] = load i128, ptr [[Y_3]], align 16
; CHECK-NEXT:    [[C_3:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_3]], i128 [[B_3]])
; CHECK-NEXT:    store i8 [[C_3]], ptr [[DST_3]], align 1
; CHECK-NEXT:    [[X_4:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 64
; CHECK-NEXT:    [[Y_4:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 64
; CHECK-NEXT:    [[DST_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 4
; CHECK-NEXT:    [[A_4:%.*]] = load i128, ptr [[X_4]], align 16
; CHECK-NEXT:    [[B_4:%.*]] = load i128, ptr [[Y_4]], align 16
; CHECK-NEXT:    [[C_4:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_4]], i128 [[B_4]])
; CHECK-NEXT:    store i8 [[C_4]], ptr [[DST_4]], align 1
; CHECK-NEXT:    [[X_5:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 80
; CHECK-NEXT:    [[Y_5:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 80
; CHECK-NEXT:    [[DST_5:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 5
; CHECK-NEXT:    [[A_5:%.*]] = load i128, ptr [[X_5]], align 16
; CHECK-NEXT:    [[B_5:%.*]] = load i128, ptr [[Y_5]], align 16
; CHECK-NEXT:    [[C_5:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_5]], i128 [[B_5]])
; CHECK-NEXT:    store i8 [[C_5]], ptr [[DST_5]], align 1
; CHECK-NEXT:    [[X_6:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 96
; CHECK-NEXT:    [[Y_6:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 96
; CHECK-NEXT:    [[DST_6:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 6
; CHECK-NEXT:    [[A_6:%.*]] = load i128, ptr [[X_6]], align 16
; CHECK-NEXT:    [[B_6:%.*]] = load i128, ptr [[Y_6]], align 16
; CHECK-NEXT:    [[C_6:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_6]], i128 [[B_6]])
; CHECK-NEXT:    store i8 [[C_6]], ptr [[DST_6]], align 1
; CHECK-NEXT:    [[X_7:%.*]] = getelementptr inbounds nuw i8, ptr [[X]], i64 112
; CHECK-NEXT:    [[Y_7:%.*]] = getelementptr inbounds nuw i8, ptr [[Y]], i64 112
; CHECK-NEXT:    [[DST_7:%.*]] = getelementptr inbounds nuw i8, ptr [[DST]], i64 7
; CHECK-NEXT:    [[A_7:%.*]] = load i128, ptr [[X_7]], align 16
; CHECK-NEXT:    [[B_7:%.*]] = load i128, ptr [[Y_7]], align 16
; CHECK-NEXT:    [[C_7:%.*]] = call i8 @llvm.ucmp.i8.i128(i128 [[A_7]], i128 [[B_7]])
; CHECK-NEXT:    store i8 [[C_7]], ptr [[DST_7]], align 1
; CHECK-NEXT:    ret void
;
  %a.0 = load i128, ptr %x, align 16
  %b.0 = load i128, ptr %y, align 16
  %c.0 = call i8 @llvm.ucmp.i8.i128(i128 %a.0, i128 %b.0)
  store i8 %c.0, ptr %dst, align 1
  %x.1 = getelementptr inbounds nuw i8, ptr %x, i64 16
  %y.1 = getelementptr inbounds nuw i8, ptr %y, i64 16
  %dst.1 = getelementptr inbounds nuw i8, ptr %dst, i64 1
  %a.1 = load i128, ptr %x.1, align 16
  %b.1 = load i128, ptr %y.1, align 16
  %c.1 = call i8 @llvm.ucmp.i8.i128(i128 %a.1, i128 %b.1)
  store i8 %c.1, ptr %dst.1, align 1
  %x.2 = getelementptr inbounds nuw i8, ptr %x, i64 32
  %y.2 = getelementptr inbounds nuw i8, ptr %y, i64 32
  %dst.2 = getelementptr inbounds nuw i8, ptr %dst, i64 2
  %a.2 = load i128, ptr %x.2, align 16
  %b.2 = load i128, ptr %y.2, align 16
  %c.2 = call i8 @llvm.ucmp.i8.i128(i128 %a.2, i128 %b.2)
  store i8 %c.2, ptr %dst.2, align 1
  %x.3 = getelementptr inbounds nuw i8, ptr %x, i64 48
  %y.3 = getelementptr inbounds nuw i8, ptr %y, i64 48
  %dst.3 = getelementptr inbounds nuw i8, ptr %dst, i64 3
  %a.3 = load i128, ptr %x.3, align 16
  %b.3 = load i128, ptr %y.3, align 16
  %c.3 = call i8 @llvm.ucmp.i8.i128(i128 %a.3, i128 %b.3)
  store i8 %c.3, ptr %dst.3, align 1
  %x.4 = getelementptr inbounds nuw i8, ptr %x, i64 64
  %y.4 = getelementptr inbounds nuw i8, ptr %y, i64 64
  %dst.4 = getelementptr inbounds nuw i8, ptr %dst, i64 4
  %a.4 = load i128, ptr %x.4, align 16
  %b.4 = load i128, ptr %y.4, align 16
  %c.4 = call i8 @llvm.ucmp.i8.i128(i128 %a.4, i128 %b.4)
  store i8 %c.4, ptr %dst.4, align 1
  %x.5 = getelementptr inbounds nuw i8, ptr %x, i64 80
  %y.5 = getelementptr inbounds nuw i8, ptr %y, i64 80
  %dst.5 = getelementptr inbounds nuw i8, ptr %dst, i64 5
  %a.5 = load i128, ptr %x.5, align 16
  %b.5 = load i128, ptr %y.5, align 16
  %c.5 = call i8 @llvm.ucmp.i8.i128(i128 %a.5, i128 %b.5)
  store i8 %c.5, ptr %dst.5, align 1
  %x.6 = getelementptr inbounds nuw i8, ptr %x, i64 96
  %y.6 = getelementptr inbounds nuw i8, ptr %y, i64 96
  %dst.6 = getelementptr inbounds nuw i8, ptr %dst, i64 6
  %a.6 = load i128, ptr %x.6, align 16
  %b.6 = load i128, ptr %y.6, align 16
  %c.6 = call i8 @llvm.ucmp.i8.i128(i128 %a.6, i128 %b.6)
  store i8 %c.6, ptr %dst.6, align 1
  %x.7 = getelementptr inbounds nuw i8, ptr %x, i64 112
  %y.7 = getelementptr inbounds nuw i8, ptr %y, i64 112
  %dst.7 = getelementptr inbounds nuw i8, ptr %dst, i64 7
  %a.7 = load i128, ptr %x.7, align 16
  %b.7 = load i128, ptr %y.7, align 16
  %c.7 = call i8 @llvm.ucmp.i8.i128(i128 %a.7, i128 %b.7)
  store i8 %c.7, ptr %dst.7, align 1
  ret void
}
