; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes='simplifycfg<switch-to-arithmetic>' -simplifycfg-require-and-preserve-domtree=1 -S | FileCheck %s --check-prefixes=CHECK,ARITH
; RUN: opt < %s -passes='simplifycfg<switch-to-lookup>' -simplifycfg-require-and-preserve-domtree=1 -S | FileCheck %s --check-prefixes=CHECK,LOOKUP

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Results that are affine in the comparison result become arithmetic on it
; rather than a chain of compares and selects.
define i32 @scmp_affine_selection(i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @scmp_affine_selection(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = call i8 @llvm.scmp.i8.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    [[SWITCH_TABLEIDX:%.*]] = sub nsw i8 [[C]], -1
; CHECK-NEXT:    [[SWITCH_IDX_CAST:%.*]] = zext i8 [[SWITCH_TABLEIDX]] to i32
; CHECK-NEXT:    [[SWITCH_IDX_MULT:%.*]] = mul nsw i32 [[SWITCH_IDX_CAST]], 2
; CHECK-NEXT:    [[SWITCH_OFFSET:%.*]] = add nsw i32 [[SWITCH_IDX_MULT]], -2
; CHECK-NEXT:    ret i32 [[SWITCH_OFFSET]]
;
entry:
  %c = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %eq
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  br label %end

eq:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ -2, %lt ], [ 0, %eq ], [ 2, %gt ]
  ret i32 %r
}

; Arbitrary results wait for lookup tables to be enabled and then use one.
define i32 @ucmp_arbitrary_selection(i32 %a, i32 %b) {
; ARITH-LABEL: define i32 @ucmp_arbitrary_selection(
; ARITH-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; ARITH-NEXT:  [[END:.*:]]
; ARITH-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[A]], [[B]]
; ARITH-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[A]], [[B]]
; ARITH-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[TMP1]], i32 17, i32 9
; ARITH-NEXT:    [[R:%.*]] = select i1 [[TMP0]], i32 5, i32 [[SPEC_SELECT]]
; ARITH-NEXT:    ret i32 [[R]]
;
; LOOKUP-LABEL: define i32 @ucmp_arbitrary_selection(
; LOOKUP-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; LOOKUP-NEXT:  [[ENTRY:.*:]]
; LOOKUP-NEXT:    [[C:%.*]] = call i8 @llvm.ucmp.i8.i32(i32 [[A]], i32 [[B]])
; LOOKUP-NEXT:    [[SWITCH_TABLEIDX:%.*]] = sub nsw i8 [[C]], -1
; LOOKUP-NEXT:    [[TMP0:%.*]] = zext nneg i8 [[SWITCH_TABLEIDX]] to i64
; LOOKUP-NEXT:    [[SWITCH_GEP:%.*]] = getelementptr inbounds [3 x i8], ptr @switch.table.ucmp_arbitrary_selection, i64 0, i64 [[TMP0]]
; LOOKUP-NEXT:    [[SWITCH_LOAD:%.*]] = load i8, ptr [[SWITCH_GEP]], align 1
; LOOKUP-NEXT:    [[SWITCH_EXT:%.*]] = zext i8 [[SWITCH_LOAD]] to i32
; LOOKUP-NEXT:    ret i32 [[SWITCH_EXT]]
;
entry:
  %c = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %eq
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  br label %end

eq:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ 5, %lt ], [ 17, %eq ], [ 9, %gt ]
  ret i32 %r
}

; Once lookup tables are enabled but declined, the switch is lowered to
; compares of the operands.
define i32 @ucmp_arbitrary_selection_no_jump_tables(i32 %a, i32 %b) "no-jump-tables"="true" {
; CHECK-LABEL: define i32 @ucmp_arbitrary_selection_no_jump_tables(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[A]], [[B]]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[A]], [[B]]
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[TMP1]], i32 17, i32 9
; CHECK-NEXT:    [[R:%.*]] = select i1 [[TMP0]], i32 5, i32 [[SPEC_SELECT]]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %c = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %eq
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  br label %end

eq:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ 5, %lt ], [ 17, %eq ], [ 9, %gt ]
  ret i32 %r
}

; Real control flow is lowered regardless of the arithmetic folds.
define void @scmp_three_destinations(i32 %a, i32 %b) {
; CHECK-LABEL: define void @scmp_three_destinations(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[LT:.*]], label %[[CMP_NEXT:.*]]
; CHECK:       [[CMP_NEXT]]:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[EQ:.*]], label %[[GT:.*]]
; CHECK:       [[COMMON_RET:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[LT]]:
; CHECK-NEXT:    call void @less()
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[EQ]]:
; CHECK-NEXT:    call void @equal()
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[GT]]:
; CHECK-NEXT:    call void @greater()
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
  %c = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %eq
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  call void @less()
  ret void

eq:
  call void @equal()
  ret void

gt:
  call void @greater()
  ret void
}

declare void @less()
declare void @equal()
declare void @greater()
