; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='slp-vectorizer,bitmask-lowering' -mtriple=x86_64-- -mcpu=x86-64-v3 < %s | FileCheck %s

; The SLP vectorizer turns the unrolled u8!=0 -> bitmask pack into
; reduce.or(shl(zext(<8 x i1>), <0..7>)); bitmask-lowering then collapses that
; to a single movemask bitcast. End-to-end: scalar pack in, movemask out.

define i8 @pack8(ptr %p) {
; CHECK-LABEL: define i8 @pack8(
; CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[G0:%.*]] = getelementptr i8, ptr [[P]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i8>, ptr [[G0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[TMP0]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    ret i8 [[TMP2]]
;
entry:
  %g0 = getelementptr i8, ptr %p, i64 0
  %g1 = getelementptr i8, ptr %p, i64 1
  %g2 = getelementptr i8, ptr %p, i64 2
  %g3 = getelementptr i8, ptr %p, i64 3
  %g4 = getelementptr i8, ptr %p, i64 4
  %g5 = getelementptr i8, ptr %p, i64 5
  %g6 = getelementptr i8, ptr %p, i64 6
  %g7 = getelementptr i8, ptr %p, i64 7
  %v0 = load i8, ptr %g0
  %v1 = load i8, ptr %g1
  %v2 = load i8, ptr %g2
  %v3 = load i8, ptr %g3
  %v4 = load i8, ptr %g4
  %v5 = load i8, ptr %g5
  %v6 = load i8, ptr %g6
  %v7 = load i8, ptr %g7
  %c0 = icmp ne i8 %v0, 0
  %c1 = icmp ne i8 %v1, 0
  %c2 = icmp ne i8 %v2, 0
  %c3 = icmp ne i8 %v3, 0
  %c4 = icmp ne i8 %v4, 0
  %c5 = icmp ne i8 %v5, 0
  %c6 = icmp ne i8 %v6, 0
  %c7 = icmp ne i8 %v7, 0
  %z0 = zext i1 %c0 to i8
  %z1 = zext i1 %c1 to i8
  %z2 = zext i1 %c2 to i8
  %z3 = zext i1 %c3 to i8
  %z4 = zext i1 %c4 to i8
  %z5 = zext i1 %c5 to i8
  %z6 = zext i1 %c6 to i8
  %z7 = zext i1 %c7 to i8
  %s0 = shl i8 %z0, 0
  %s1 = shl i8 %z1, 1
  %s2 = shl i8 %z2, 2
  %s3 = shl i8 %z3, 3
  %s4 = shl i8 %z4, 4
  %s5 = shl i8 %z5, 5
  %s6 = shl i8 %z6, 6
  %s7 = shl i8 %z7, 7
  %o0 = or i8 %s0, %s1
  %o1 = or i8 %o0, %s2
  %o2 = or i8 %o1, %s3
  %o3 = or i8 %o2, %s4
  %o4 = or i8 %o3, %s5
  %o5 = or i8 %o4, %s6
  %o6 = or i8 %o5, %s7
  ret i8 %o6
}
