; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 -verify-dom-info -verify-each -S | FileCheck %s --check-prefixes=CHECK,EARLY
; RUN: opt < %s -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=0 -verify-each -S | FileCheck %s --check-prefixes=CHECK,EARLY
; RUN: opt < %s -passes='simplifycfg<switch-to-lookup>' -simplifycfg-require-and-preserve-domtree=1 -verify-dom-info -verify-each -S | FileCheck %s --check-prefixes=CHECK,LATE

define void @ucmp_gt1(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt1(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt2(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt2(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 0, label %bb2
  i8 -1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_lt1(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_lt1(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp uge i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb2 [
  i8 1, label %bb1
  i8 0, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_lt2(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_lt2(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp uge i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb2 [
  i8 0, label %bb1
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_eq1(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_eq1(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_eq2(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_eq2(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 1, label %bb2
  i8 -1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @scmp_gt1(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @scmp_gt1(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sle i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @scmp_gt2(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @scmp_gt2(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sle i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 0, label %bb2
  i8 -1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_multiuse(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_multiuse(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i8 @llvm.ucmp.i8.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    call void @use(i8 [[RES]])
; CHECK-NEXT:    switch i8 [[RES]], label %[[BB1:.*]] [
; CHECK-NEXT:      i8 -1, label %[[BB2:.*]]
; CHECK-NEXT:      i8 0, label %[[BB2]]
; CHECK-NEXT:    ]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  call void @use(i8 %res)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define i32 @ucmp_gt_phi(i32 %a, i32 %b) {
;
; CHECK-LABEL: define i32 @ucmp_gt_phi(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ 0, %[[BB1]] ], [ 1, %[[ENTRY]] ]
; CHECK-NEXT:    ret i32 [[PHI]]
;
entry:
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  %phi = phi i32 [ 0, %bb1 ], [ 1, %entry ], [ 1, %entry ]
  ret i32 %phi
}

define void @ucmp_gt_extra_case(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_extra_case(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[BB2:.*:]]
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  i8 1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_wrong_case(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_wrong_case(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i8 @llvm.ucmp.i8.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    switch i8 [[RES]], label %[[BB1:.*]] [
; CHECK-NEXT:      i8 -2, label %[[BB2:.*]]
; CHECK-NEXT:      i8 0, label %[[BB2]]
; CHECK-NEXT:    ]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -2, label %bb2
  i8 0, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_not_same_succ(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_not_same_succ(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[CMP_NEXT:.*]]
; CHECK:       [[CMP_NEXT]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb3
  ]

bb1:
  call void @foo()
  br label %bb2

bb3:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_unpredictable(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unpredictable(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]], !unpredictable [[META0:![0-9]+]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ], !unpredictable !{}

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_weights(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_weights(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]], !prof [[PROF1:![0-9]+]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %bb1 [
  i8 -1, label %bb2
  i8 0, label %bb2
  ], !prof !{!"branch_weights", i32 5, i32 10, i32 20}

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void
}

define void @ucmp_gt_unreachable(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb2
  i8 0, label %bb2
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

define void @ucmp_lt_unreachable(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_lt_unreachable(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB1:.*]], label %[[BB2:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb1
  i8 0, label %bb2
  i8 1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

define void @ucmp_eq_unreachable(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_eq_unreachable(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb2
  i8 0, label %bb1
  i8 1, label %bb2
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

define void @ucmp_gt_unreachable_multi_edge(i8 %x, i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_multi_edge(
; CHECK-SAME: i8 [[X:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i8 [[X]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i8 0, label %[[SW:.*]]
; CHECK-NEXT:      i8 1, label %[[BB1:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[BB2:.*]], label %[[BB1]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
entry:
  switch i8 %x, label %unreachable [
  i8 0, label %sw
  i8 1, label %bb1
  ]

sw:
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb2
  i8 0, label %bb2
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  %phi = phi i32 [ 0, %entry ], [ 1, %sw ]
  unreachable
}

define void @ucmp_gt_unreachable_wrong_case(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_wrong_case(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[RES:%.*]] = call i8 @llvm.ucmp.i8.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    switch i8 [[RES]], label %[[UNREACHABLE:.*]] [
; CHECK-NEXT:      i8 -2, label %[[BB2:.*]]
; CHECK-NEXT:      i8 0, label %[[BB2]]
; CHECK-NEXT:      i8 1, label %[[BB1:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -2, label %bb2
  i8 0, label %bb2
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

define void @ucmp_gt_unreachable_no_two_equal_cases(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_no_two_equal_cases(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB3:.*]], label %[[CMP_NEXT:.*]]
; CHECK:       [[CMP_NEXT]]:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP2]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb3
  i8 0, label %bb2
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb3:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

define void @ucmp_gt_unreachable_three_equal_cases(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_three_equal_cases(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[BB1:.*:]]
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb1
  i8 0, label %bb1
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  ret void

unreachable:
  unreachable
}

define void @ucmp_gt_unreachable_default_not_unreachable(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_default_not_unreachable(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %not.unreachable [
  i8 -1, label %bb2
  i8 0, label %bb2
  i8 1, label %bb1
  ]

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

not.unreachable:
  call void @foo()
  br label %bb2
}

define void @ucmp_gt_unreachable_weights(i32 %a, i32 %b) {
;
; CHECK-LABEL: define void @ucmp_gt_unreachable_weights(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[BB2:.*]], label %[[BB1:.*]], !prof [[PROF1]]
; CHECK:       [[BB1]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[BB2]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    ret void
;
  %res = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %res, label %unreachable [
  i8 -1, label %bb2
  i8 0, label %bb2
  i8 1, label %bb1
  ], !prof !{!"branch_weights", i32 0, i32 10, i32 20, i32 5}

bb1:
  call void @foo()
  br label %bb2

bb2:
  ret void

unreachable:
  unreachable
}

; Three distinct destinations, including a direct edge to the result PHI.
; The branch chain should expose the comparisons to subsequent select folding.
define i64 @ucmp_three_destinations_phi_select(i8 %x, i8 %y) {
; CHECK-LABEL: define i64 @ucmp_three_destinations_phi_select(
; CHECK-SAME: i8 [[X:%.*]], i8 [[Y:%.*]]) {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i8 [[X]], [[Y]]
; CHECK-NEXT:    [[Z:%.*]] = zext i8 [[X]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i8 [[X]], [[Y]]
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[TMP1]], i64 4, i64 2
; CHECK-NEXT:    [[R:%.*]] = select i1 [[TMP0]], i64 [[Z]], i64 [[SPEC_SELECT]]
; CHECK-NEXT:    ret i64 [[R]]
;
start:
  %c = call i8 @llvm.ucmp.i8.i8(i8 %x, i8 %y)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %end
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  %z = zext i8 %x to i64
  br label %end

gt:
  br label %end

end:
  %r = phi i64 [ %z, %lt ], [ 2, %gt ], [ 4, %start ]
  ret i64 %r
}

; Arms that only select constants into one PHI are left alone until the
; arithmetic and lookup table folds have run, then lowered if they declined.
define i32 @ucmp_constant_selection_deferred(i32 %a, i32 %b) {
; EARLY-LABEL: define i32 @ucmp_constant_selection_deferred(
; EARLY-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; EARLY-NEXT:  [[ENTRY:.*]]:
; EARLY-NEXT:    [[C:%.*]] = call i8 @llvm.ucmp.i8.i32(i32 [[A]], i32 [[B]])
; EARLY-NEXT:    switch i8 [[C]], label %[[UNR:.*]] [
; EARLY-NEXT:      i8 -1, label %[[END:.*]]
; EARLY-NEXT:      i8 0, label %[[EQ:.*]]
; EARLY-NEXT:      i8 1, label %[[GT:.*]]
; EARLY-NEXT:    ]
; EARLY:       [[UNR]]:
; EARLY-NEXT:    unreachable
; EARLY:       [[EQ]]:
; EARLY-NEXT:    br label %[[END]]
; EARLY:       [[GT]]:
; EARLY-NEXT:    br label %[[END]]
; EARLY:       [[END]]:
; EARLY-NEXT:    [[R:%.*]] = phi i32 [ 9, %[[GT]] ], [ 17, %[[EQ]] ], [ 5, %[[ENTRY]] ]
; EARLY-NEXT:    ret i32 [[R]]
;
; LATE-LABEL: define i32 @ucmp_constant_selection_deferred(
; LATE-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; LATE-NEXT:  [[ENTRY:.*:]]
; LATE-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[A]], [[B]]
; LATE-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[A]], [[B]]
; LATE-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[TMP1]], i32 17, i32 9
; LATE-NEXT:    [[R:%.*]] = select i1 [[TMP0]], i32 5, i32 [[SPEC_SELECT]]
; LATE-NEXT:    ret i32 [[R]]
;
entry:
  %c = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %unr [
  i8 -1, label %lt
  i8 0, label %eq
  i8 1, label %gt
  ]

unr:
  unreachable

lt:
  br label %end

eq:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ 5, %lt ], [ 17, %eq ], [ 9, %gt ]
  ret i32 %r
}

; A reachable default that also selects a constant is deferred too; the
; switch to select fold then takes it.
define i32 @scmp_constant_selection_default(i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @scmp_constant_selection_default(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[C:%.*]] = call i8 @llvm.scmp.i8.i32(i32 [[A]], i32 [[B]])
; CHECK-NEXT:    [[SWITCH_SELECTCMP:%.*]] = icmp eq i8 [[C]], 1
; CHECK-NEXT:    [[SWITCH_SELECT:%.*]] = select i1 [[SWITCH_SELECTCMP]], i32 9, i32 17
; CHECK-NEXT:    [[SWITCH_SELECTCMP1:%.*]] = icmp eq i8 [[C]], -1
; CHECK-NEXT:    [[SWITCH_SELECT2:%.*]] = select i1 [[SWITCH_SELECTCMP1]], i32 5, i32 [[SWITCH_SELECT]]
; CHECK-NEXT:    ret i32 [[SWITCH_SELECT2]]
;
entry:
  %c = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %end [
  i8 -1, label %lt
  i8 1, label %gt
  ]

lt:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ 5, %lt ], [ 9, %gt ], [ 17, %entry ]
  ret i32 %r
}

; A default with side effects is real control flow and is lowered right away.
define i32 @scmp_constant_cases_side_effect_default(i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @scmp_constant_cases_side_effect_default(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp slt i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[END:.*]], label %[[CMP_NEXT:.*]]
; CHECK:       [[CMP_NEXT]]:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[A]], [[B]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[END]], label %[[DEF:.*]]
; CHECK:       [[DEF]]:
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    br label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    [[R:%.*]] = phi i32 [ 17, %[[DEF]] ], [ 5, %[[ENTRY]] ], [ 9, %[[CMP_NEXT]] ]
; CHECK-NEXT:    ret i32 [[R]]
;
entry:
  %c = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %c, label %def [
  i8 -1, label %lt
  i8 1, label %gt
  ]

def:
  call void @foo()
  br label %end

lt:
  br label %end

gt:
  br label %end

end:
  %r = phi i32 [ 5, %lt ], [ 9, %gt ], [ 17, %def ]
  ret i32 %r
}

; Keep the following checks focused on each regression's specific behavior.
; UTC_ARGS: --disable

; Sort by weight, preserve signed comparisons, and weight each remaining branch.
define void @three_destinations_weighted_signed(i32 %a, i32 %b) {
; CHECK-LABEL: define void @three_destinations_weighted_signed(
; CHECK: [[SIGNED_LT:%.*]] = icmp slt i32 %a, %b
; CHECK-NEXT: br i1 [[SIGNED_LT]], label %less, label %[[SIGNED_NEXT:.*]], !prof [[THREE_FIRST:![0-9]+]]
; CHECK: [[SIGNED_NEXT]]:
; CHECK-NEXT: [[SIGNED_GT:%.*]] = icmp sgt i32 %a, %b
; CHECK-NEXT: br i1 [[SIGNED_GT]], label %greater, label %equal, !prof [[THREE_SECOND:![0-9]+]]
  %cmp = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 0, label %equal
  i8 1, label %greater
  i8 -1, label %less
  ], !prof !{!"branch_weights", i32 0, i32 10, i32 30, i32 60}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
less:
  call void @less()
  ret void
dead:
  unreachable
}

; Tied weights preserve case order; both branches retain unpredictable metadata.
define void @three_destinations_tied(i32 %a, i32 %b) {
; CHECK-LABEL: define void @three_destinations_tied(
; CHECK: [[TIED_EQ:%.*]] = icmp eq i32 %a, %b
; CHECK-NEXT: br i1 [[TIED_EQ]], label %equal, label %[[TIED_NEXT:.*]], !prof {{![0-9]+}}, !unpredictable [[META0]]
; CHECK: [[TIED_NEXT]]:
; CHECK-NEXT: [[TIED_GT:%.*]] = icmp ugt i32 %a, %b
; CHECK-NEXT: br i1 [[TIED_GT]], label %greater, label %less, !prof {{![0-9]+}}, !unpredictable [[META0]]
  %cmp = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %less [
  i8 0, label %equal
  i8 1, label %greater
  ], !prof !{!"branch_weights", i32 10, i32 10, i32 10}, !unpredictable !{}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
less:
  call void @less()
  ret void
}

; The hottest destination can be the default covering the missing result.
define void @two_cases_hot_default(i32 %a, i32 %b) {
; CHECK-LABEL: define void @two_cases_hot_default(
; CHECK: [[DEFAULT_LT:%.*]] = icmp slt i32 %a, %b
; CHECK-NEXT: br i1 [[DEFAULT_LT]], label %less, label %{{.*}}, !prof [[THREE_FIRST]]
  %cmp = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %less [
  i8 0, label %equal
  i8 1, label %greater
  ], !prof !{!"branch_weights", i32 60, i32 10, i32 30}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
less:
  call void @less()
  ret void
}

; Merge before sorting, using a wide sum and fitting the resulting weights.
define void @merged_weights_overflow(i32 %a, i32 %b) {
; CHECK-LABEL: define void @merged_weights_overflow(
; CHECK: [[MERGED_LE:%.*]] = icmp sle i32 %a, %b
; CHECK-NEXT: br i1 [[MERGED_LE]], label %other, label %greater, !prof [[MERGED_WEIGHTS:![0-9]+]]
  %cmp = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 1, label %greater
  i8 0, label %other
  i8 -1, label %other
  ], !prof !{!"branch_weights", i32 0, i32 4000000000, i32 3000000000, i32 3000000000}
other:
  call void @less()
  ret void
greater:
  call void @greater()
  ret void
dead:
  unreachable
}

; Bail out when a possible result is covered only by an unreachable default.
define void @two_cases_unreachable_default(i32 %a, i32 %b) {
; CHECK-LABEL: define void @two_cases_unreachable_default(
; CHECK: [[UNCOVERED_CMP:%.*]] = call i8 @llvm.ucmp.i8.i32
; CHECK-NEXT: switch i8 [[UNCOVERED_CMP]], label %dead [
; CHECK-NEXT: i8 0, label %equal
; CHECK-NEXT: i8 1, label %greater
; CHECK: dead:
; CHECK-NEXT: unreachable
  %cmp = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 0, label %equal
  i8 1, label %greater
  ], !prof !{!"branch_weights", i32 0, i32 20, i32 10}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
dead:
  unreachable
}

; Bail out on a case value too wide for int64_t, even after collecting valid cases.
define void @impossible_wide_cases(i32 %a, i32 %b) {
; CHECK-LABEL: define void @impossible_wide_cases(
; CHECK: [[WIDE_CMP:%.*]] = call i128 @llvm.ucmp.i128.i32
; CHECK-NEXT: switch i128 [[WIDE_CMP]], label %greater [
; CHECK: i128 18446744073709551616, label %dead
; CHECK: i128 -2, label %dead
  %cmp = call i128 @llvm.ucmp.i128.i32(i32 %a, i32 %b)
  switch i128 %cmp, label %greater [
  i128 -1, label %less
  i128 0, label %equal
  i128 18446744073709551616, label %dead
  i128 -2, label %dead
  ], !prof !{!"branch_weights", i32 30, i32 60, i32 10, i32 100, i32 100}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
less:
  call void @less()
  ret void
dead:
  call void @impossible()
  ret void
}

; Move only the later arms' PHI entries; preserve the first arm and other preds.
define i32 @three_destinations_phi(i8 %x, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @three_destinations_phi(
; CHECK: sw:
; CHECK: br i1 {{%.*}}, label %equal, label %[[PHI_NEXT:.*]],
; CHECK: [[PHI_NEXT]]:
; CHECK: br i1 {{%.*}}, label %greater, label %less
; CHECK: %e = phi i32 [ 1, %entry ], [ 2, %sw ]{{$}}
; CHECK: %g = phi i32 [ 3, %entry ], [ 4, %[[PHI_NEXT]] ]{{$}}
; CHECK: %l = phi i32 [ 5, %entry ], [ 6, %[[PHI_NEXT]] ]{{$}}
entry:
  switch i8 %x, label %dead [
  i8 0, label %sw
  i8 1, label %equal
  i8 2, label %greater
  i8 3, label %less
  ]
sw:
  %cmp = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 0, label %equal
  i8 1, label %greater
  i8 -1, label %less
  ], !prof !{!"branch_weights", i32 0, i32 60, i32 30, i32 10}
equal:
  %e = phi i32 [ 1, %entry ], [ 2, %sw ]
  call void @equal()
  ret i32 %e
greater:
  %g = phi i32 [ 3, %entry ], [ 4, %sw ]
  call void @greater()
  ret i32 %g
less:
  %l = phi i32 [ 5, %entry ], [ 6, %sw ]
  call void @less()
  ret i32 %l
dead:
  %d = phi i32 [ 7, %entry ], [ 8, %sw ]
  unreachable
}

; A moved loop backedge must update the header PHI's predecessor.
define void @three_destinations_loop(i32 %start, i32 %b) {
; CHECK-LABEL: define void @three_destinations_loop(
; CHECK: %a = phi i32 [ %start, %entry ], [ %next, %[[LOOP_NEXT:.*]] ]
; CHECK: [[LOOP_NEXT]]:
; CHECK: br i1 {{%.*}}, label %greater, label %loop
entry:
  br label %loop
loop:
  %a = phi i32 [ %start, %entry ], [ %next, %loop ]
  %next = add i32 %a, 1
  %cmp = call i8 @llvm.scmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 0, label %equal
  i8 1, label %greater
  i8 -1, label %loop
  ]
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
dead:
  unreachable
}

; Retain one PHI entry for merged cases and leave other predecessors unchanged.
define i32 @merged_destination_phis(i8 %x, i32 %a, i32 %b) {
; CHECK-LABEL: define i32 @merged_destination_phis(
; CHECK: %o = phi i32 [ 1, %entry ], [ 2, %sw ]{{$}}
; CHECK: %g = phi i32 [ 3, %entry ], [ 4, %sw ]{{$}}
entry:
  switch i8 %x, label %sw [
  i8 0, label %other
  i8 1, label %greater
  ]
sw:
  %cmp = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 1, label %greater
  i8 0, label %other
  i8 -1, label %other
  ], !prof !{!"branch_weights", i32 0, i32 40, i32 30, i32 30}
other:
  %o = phi i32 [ 1, %entry ], [ 2, %sw ], [ 2, %sw ]
  call void @less()
  ret i32 %o
greater:
  %g = phi i32 [ 3, %entry ], [ 4, %sw ]
  call void @greater()
  ret i32 %g
dead:
  unreachable
}

; Preserve llvm.expect provenance on both generated branches.
define void @three_destinations_expected(i32 %a, i32 %b) {
; CHECK-LABEL: define void @three_destinations_expected(
; CHECK: br i1 {{%.*}}, label %less, label %{{.*}}, !prof [[EXPECTED_FIRST:![0-9]+]]
; CHECK: br i1 {{%.*}}, label %greater, label %equal, !prof [[EXPECTED_SECOND:![0-9]+]]
  %cmp = call i8 @llvm.ucmp.i8.i32(i32 %a, i32 %b)
  switch i8 %cmp, label %dead [
  i8 0, label %equal
  i8 1, label %greater
  i8 -1, label %less
  ], !prof !{!"branch_weights", !"expected", i32 0, i32 10, i32 30, i32 60}
equal:
  call void @equal()
  ret void
greater:
  call void @greater()
  ret void
less:
  call void @less()
  ret void
dead:
  unreachable
}

declare void @equal()
declare void @greater()
declare void @less()
declare void @impossible()


declare void @use(i8)
declare void @foo()
;.
; CHECK: [[META0]] = !{}
; CHECK: [[PROF1]] = !{!"branch_weights", i32 30, i32 5}
; CHECK-DAG: [[THREE_FIRST]] = !{!"branch_weights", i32 60, i32 40}
; CHECK-DAG: [[THREE_SECOND]] = !{!"branch_weights", i32 30, i32 10}
; CHECK-DAG: [[MERGED_WEIGHTS]] = !{!"branch_weights", i32 -1294967296, i32 2000000000}
; CHECK-DAG: [[EXPECTED_FIRST]] = !{!"branch_weights", !"expected", i32 60, i32 40}
; CHECK-DAG: [[EXPECTED_SECOND]] = !{!"branch_weights", !"expected", i32 30, i32 10}
;.
