; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-- < %s | FileCheck %s

; The compare->bitmask idiom in its various vectorized shapes should collapse to
; a single `bitcast <N x i1> to iN` (which the x86 backend lowers to a movemask).

declare i8 @llvm.vector.reduce.or.v8i8(<8 x i8>)
declare i32 @llvm.vector.reduce.or.v8i32(<8 x i32>)
declare i64 @llvm.vector.reduce.or.v64i64(<64 x i64>)
declare i8 @llvm.vector.reduce.add.v8i8(<8 x i8>)
declare i8 @llvm.vector.reduce.xor.v8i8(<8 x i8>)

; select %m, <1,2,4,...,128>, zeroinitializer  ->  bitcast to i8
define i8 @select_form_i8(<8 x i1> %m) {
; CHECK-LABEL: @select_form_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Wider element type: bitcast to i8, then zext to i32.
define i32 @select_form_i32(<8 x i1> %m) {
; CHECK-LABEL: @select_form_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    [[R:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i32> <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>, <8 x i32> zeroinitializer
  %r = call i32 @llvm.vector.reduce.or.v8i32(<8 x i32> %sel)
  ret i32 %r
}

; shl (zext %m), <0,1,2,...,7>
define i8 @shl_form_i8(<8 x i1> %m) {
; CHECK-LABEL: @shl_form_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %z = zext <8 x i1> %m to <8 x i8>
  %shl = shl <8 x i8> %z, <i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %shl)
  ret i8 %r
}

; and (sext %m), <1,2,4,...,128>
define i8 @and_form_i8(<8 x i1> %m) {
; CHECK-LABEL: @and_form_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %s = sext <8 x i1> %m to <8 x i8>
  %and = and <8 x i8> %s, <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %and)
  ret i8 %r
}

; mul (zext %m), <1,2,4,...,128>
define i8 @mul_form_i8(<8 x i1> %m) {
; CHECK-LABEL: @mul_form_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %z = zext <8 x i1> %m to <8 x i8>
  %mul = mul <8 x i8> %z, <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %mul)
  ret i8 %r
}

; reduce.add is equivalent because the lane contributions are disjoint bits.
define i8 @add_reduce_i8(<8 x i1> %m) {
; CHECK-LABEL: @add_reduce_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.add.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; reduce.xor is likewise equivalent.
define i8 @xor_reduce_i8(<8 x i1> %m) {
; CHECK-LABEL: @xor_reduce_i8(
; CHECK-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.xor.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; The 64-lane u8-packing case from the motivating Vortex workload.
define i64 @select_form_i64_n64(<64 x i1> %m) {
; CHECK-LABEL: @select_form_i64_n64(
; CHECK-NEXT:    [[R:%.*]] = bitcast <64 x i1> [[M:%.*]] to i64
; CHECK-NEXT:    ret i64 [[R]]
;
  %sel = select <64 x i1> %m, <64 x i64> <i64 1, i64 2, i64 4, i64 8, i64 16, i64 32, i64 64, i64 128, i64 256, i64 512, i64 1024, i64 2048, i64 4096, i64 8192, i64 16384, i64 32768, i64 65536, i64 131072, i64 262144, i64 524288, i64 1048576, i64 2097152, i64 4194304, i64 8388608, i64 16777216, i64 33554432, i64 67108864, i64 134217728, i64 268435456, i64 536870912, i64 1073741824, i64 2147483648, i64 4294967296, i64 8589934592, i64 17179869184, i64 34359738368, i64 68719476736, i64 137438953472, i64 274877906944, i64 549755813888, i64 1099511627776, i64 2199023255552, i64 4398046511104, i64 8796093022208, i64 17592186044416, i64 35184372088832, i64 70368744177664, i64 140737488355328, i64 281474976710656, i64 562949953421312, i64 1125899906842624, i64 2251799813685248, i64 4503599627370496, i64 9007199254740992, i64 18014398509481984, i64 36028797018963968, i64 72057594037927936, i64 144115188075855872, i64 288230376151711744, i64 576460752303423488, i64 1152921504606846976, i64 2305843009213693952, i64 4611686018427387904, i64 -9223372036854775808>, <64 x i64> zeroinitializer
  %r = call i64 @llvm.vector.reduce.or.v64i64(<64 x i64> %sel)
  ret i64 %r
}
