; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes='slp-vectorizer,vector-combine' -mtriple=x86_64-- -mcpu=x86-64-v3 < %s | FileCheck %s

; A loop over output words whose inner 8-lane pack is straight-line code.
; LoopVectorize cannot vectorize the bit-pack reduction (see loop-not-vectorized.ll),
; but SLP vectorizes the inner pack and bitmask-lowering turns it into a movemask
; INSIDE the loop body -- the practical way the loop idiom gets handled.

define void @pack_words(ptr noalias %out, ptr noalias %in, i64 %nwords) {
; CHECK-LABEL: define void @pack_words(
; CHECK-SAME: ptr noalias [[OUT:%.*]], ptr noalias [[IN:%.*]], i64 [[NWORDS:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[Z:%.*]] = icmp eq i64 [[NWORDS]], 0
; CHECK-NEXT:    br i1 [[Z]], label %[[EXIT:.*]], label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[W:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[W_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[BASE:%.*]] = mul i64 [[W]], 8
; CHECK-NEXT:    [[P0:%.*]] = getelementptr i8, ptr [[IN]], i64 [[BASE]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i8>, ptr [[P0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i8> [[TMP0]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    [[OUTP:%.*]] = getelementptr i8, ptr [[OUT]], i64 [[W]]
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[OUTP]], align 1
; CHECK-NEXT:    [[W_NEXT]] = add i64 [[W]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[W_NEXT]], [[NWORDS]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %z = icmp eq i64 %nwords, 0
  br i1 %z, label %exit, label %loop
loop:
  %w = phi i64 [0, %entry], [%w.next, %loop]
  %base = mul i64 %w, 8
  %p0 = getelementptr i8, ptr %in, i64 %base
  %b1 = add i64 %base, 1
  %p1 = getelementptr i8, ptr %in, i64 %b1
  %b2 = add i64 %base, 2
  %p2 = getelementptr i8, ptr %in, i64 %b2
  %b3 = add i64 %base, 3
  %p3 = getelementptr i8, ptr %in, i64 %b3
  %b4 = add i64 %base, 4
  %p4 = getelementptr i8, ptr %in, i64 %b4
  %b5 = add i64 %base, 5
  %p5 = getelementptr i8, ptr %in, i64 %b5
  %b6 = add i64 %base, 6
  %p6 = getelementptr i8, ptr %in, i64 %b6
  %b7 = add i64 %base, 7
  %p7 = getelementptr i8, ptr %in, i64 %b7
  %v0 = load i8, ptr %p0
  %v1 = load i8, ptr %p1
  %v2 = load i8, ptr %p2
  %v3 = load i8, ptr %p3
  %v4 = load i8, ptr %p4
  %v5 = load i8, ptr %p5
  %v6 = load i8, ptr %p6
  %v7 = load i8, ptr %p7
  %c0 = icmp ne i8 %v0, 0
  %c1 = icmp ne i8 %v1, 0
  %c2 = icmp ne i8 %v2, 0
  %c3 = icmp ne i8 %v3, 0
  %c4 = icmp ne i8 %v4, 0
  %c5 = icmp ne i8 %v5, 0
  %c6 = icmp ne i8 %v6, 0
  %c7 = icmp ne i8 %v7, 0
  %z0 = zext i1 %c0 to i8
  %z1 = zext i1 %c1 to i8
  %z2 = zext i1 %c2 to i8
  %z3 = zext i1 %c3 to i8
  %z4 = zext i1 %c4 to i8
  %z5 = zext i1 %c5 to i8
  %z6 = zext i1 %c6 to i8
  %z7 = zext i1 %c7 to i8
  %s1 = shl i8 %z1, 1
  %s2 = shl i8 %z2, 2
  %s3 = shl i8 %z3, 3
  %s4 = shl i8 %z4, 4
  %s5 = shl i8 %z5, 5
  %s6 = shl i8 %z6, 6
  %s7 = shl i8 %z7, 7
  %o0 = or i8 %z0, %s1
  %o1 = or i8 %o0, %s2
  %o2 = or i8 %o1, %s3
  %o3 = or i8 %o2, %s4
  %o4 = or i8 %o3, %s5
  %o5 = or i8 %o4, %s6
  %word = or i8 %o5, %s7
  %outp = getelementptr i8, ptr %out, i64 %w
  store i8 %word, ptr %outp
  %w.next = add i64 %w, 1
  %done = icmp eq i64 %w.next, %nwords
  br i1 %done, label %exit, label %loop
exit:
  ret void
}
