; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=vector-combine -mtriple=x86_64-- < %s | FileCheck %s

declare i8 @llvm.vector.reduce.or.v8i8(<8 x i8>)
declare i8 @llvm.vector.reduce.and.v8i8(<8 x i8>)

; Weights are not the 1<<i ramp: not a movemask, leave alone.
define i8 @not_power_of_two(<8 x i1> %m) {
; CHECK-LABEL: @not_power_of_two(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 65>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 65>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Reversed bit weights (lane i owns bit N-1-i) is a bit-reversed movemask, not a
; plain bitcast: leave alone.
define i8 @reversed_weights(<8 x i1> %m) {
; CHECK-LABEL: @reversed_weights(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 -128, i8 64, i8 32, i8 16, i8 8, i8 4, i8 2, i8 1>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 -128, i8 64, i8 32, i8 16, i8 8, i8 4, i8 2, i8 1>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Non-zero false arm: not the idiom.
define i8 @nonzero_false_arm(<8 x i1> %m) {
; CHECK-LABEL: @nonzero_false_arm(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> splat (i8 1)
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> <i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; reduce.and is not a bitwise OR of disjoint bits: not the idiom.
define i8 @and_reduce(<8 x i1> %m) {
; CHECK-LABEL: @and_reduce(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.and.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.and.v8i8(<8 x i8> %sel)
  ret i8 %r
}
