; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mcpu=cortex-a510 -aarch64-enable-atomic-cfg-tidy=0 < %s | FileCheck %s --check-prefixes=A510
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mcpu=apple-m1 -aarch64-enable-atomic-cfg-tidy=0 < %s | FileCheck %s --check-prefixes=M1

; Reduced from rust-lang/rust#162074. Both legs compute the same expression,
; one specialised to a constant divisor and one dividing by the runtime value,
; so their critical paths are nearly identical and the per-PHI critical path
; check sees almost no extension. Merging them makes the specialised leg pay
; for the sdivs it exists to avoid, which loses at every branch probability,
; so the branch has to survive.

define i64 @mul_div_i64(i64 %value, i64 range(i64 1, 0) %denom) {
; A510-LABEL: mul_div_i64:
; A510:       // %bb.0: // %start
; A510-NEXT:    mov w9, #13824 // =0x3600
; A510-NEXT:    mov w8, #51712 // =0xca00
; A510-NEXT:    movk w9, #366, lsl #16
; A510-NEXT:    movk w8, #15258, lsl #16
; A510-NEXT:    cmp x1, x9
; A510-NEXT:    b.ne .LBB0_2
; A510-NEXT:  // %bb.1: // %bb1
; A510-NEXT:    mov x10, #36083 // =0x8cf3
; A510-NEXT:    movk x10, #38032, lsl #16
; A510-NEXT:    movk x10, #64519, lsl #32
; A510-NEXT:    movk x10, #45812, lsl #48
; A510-NEXT:    smulh x11, x0, x10
; A510-NEXT:    add x11, x11, x0
; A510-NEXT:    asr x12, x11, #24
; A510-NEXT:    add x11, x12, x11, lsr #63
; A510-NEXT:    msub x9, x11, x9, x0
; A510-NEXT:    mul x9, x9, x8
; A510-NEXT:    smulh x10, x9, x10
; A510-NEXT:    add x9, x10, x9
; A510-NEXT:    asr x10, x9, #24
; A510-NEXT:    add x9, x10, x9, lsr #63
; A510-NEXT:    madd x0, x11, x8, x9
; A510-NEXT:    ret
; A510-NEXT:  .LBB0_2: // %bb2
; A510-NEXT:    sdiv x9, x0, x1
; A510-NEXT:    msub x10, x9, x1, x0
; A510-NEXT:    mul x10, x10, x8
; A510-NEXT:    sdiv x10, x10, x1
; A510-NEXT:    madd x0, x9, x8, x10
; A510-NEXT:    ret
;
; M1-LABEL: mul_div_i64:
; M1:       // %bb.0: // %start
; M1-NEXT:    mov w8, #51712 // =0xca00
; M1-NEXT:    movk w8, #15258, lsl #16
; M1-NEXT:    mov w9, #13824 // =0x3600
; M1-NEXT:    movk w9, #366, lsl #16
; M1-NEXT:    cmp x1, x9
; M1-NEXT:    b.ne .LBB0_2
; M1-NEXT:  // %bb.1: // %bb1
; M1-NEXT:    mov x10, #36083 // =0x8cf3
; M1-NEXT:    movk x10, #38032, lsl #16
; M1-NEXT:    movk x10, #64519, lsl #32
; M1-NEXT:    movk x10, #45812, lsl #48
; M1-NEXT:    smulh x11, x0, x10
; M1-NEXT:    add x11, x11, x0
; M1-NEXT:    asr x12, x11, #24
; M1-NEXT:    add x11, x12, x11, lsr #63
; M1-NEXT:    msub x9, x11, x9, x0
; M1-NEXT:    mul x9, x9, x8
; M1-NEXT:    smulh x10, x9, x10
; M1-NEXT:    add x9, x10, x9
; M1-NEXT:    asr x10, x9, #24
; M1-NEXT:    add x9, x10, x9, lsr #63
; M1-NEXT:    madd x0, x11, x8, x9
; M1-NEXT:    ret
; M1-NEXT:  .LBB0_2: // %bb2
; M1-NEXT:    sdiv x9, x0, x1
; M1-NEXT:    msub x10, x9, x1, x0
; M1-NEXT:    mul x10, x10, x8
; M1-NEXT:    sdiv x10, x10, x1
; M1-NEXT:    madd x0, x9, x8, x10
; M1-NEXT:    ret
start:
  %c = icmp eq i64 %denom, 24000000
  br i1 %c, label %bb1, label %bb2

bb1:
  %q1 = sdiv i64 %value, 24000000
  %m1 = mul i64 %q1, 24000000
  %r1 = sub i64 %value, %m1
  %rn1 = mul nsw i64 %r1, 1000000000
  %qn1 = mul i64 %q1, 1000000000
  %d1 = sdiv i64 %rn1, 24000000
  %o1 = add i64 %d1, %qn1
  br label %bb3

bb2:
  %q2 = sdiv i64 %value, %denom
  %m2 = mul i64 %q2, %denom
  %r2 = sub i64 %value, %m2
  %rn2 = mul i64 %r2, 1000000000
  %qn2 = mul i64 %q2, 1000000000
  %d2 = sdiv i64 %rn2, %denom
  %o2 = add i64 %qn2, %d2
  br label %bb3

bb3:
  %p = phi i64 [ %o1, %bb1 ], [ %o2, %bb2 ]
  ret i64 %p
}

; Both legs are a single cheap instruction, so speculating them costs far less
; than a misprediction. This must still be if-converted.

define i64 @cheap_legs(i64 %a, i64 %b, i64 %c) {
; A510-LABEL: cheap_legs:
; A510:       // %bb.0: // %entry
; A510-NEXT:    sub x8, x0, x2
; A510-NEXT:    add x9, x0, x2
; A510-NEXT:    cmp x0, x1
; A510-NEXT:    csel x0, x8, x9, le
; A510-NEXT:    ret
;
; M1-LABEL: cheap_legs:
; M1:       // %bb.0: // %entry
; M1-NEXT:    sub x8, x0, x2
; M1-NEXT:    add x9, x0, x2
; M1-NEXT:    cmp x0, x1
; M1-NEXT:    csel x0, x8, x9, le
; M1-NEXT:    ret
entry:
  %cmp = icmp sgt i64 %a, %b
  br i1 %cmp, label %t, label %f

t:
  %x = add i64 %a, %c
  br label %join

f:
  %y = sub i64 %a, %c
  br label %join

join:
  %p = phi i64 [ %x, %t ], [ %y, %f ]
  ret i64 %p
}

; Not division-specific: two legs of equal-latency multiply chains. The old
; model saw no critical path extension because the legs match, so it merged
; them and duplicated both chains. Keeping the branch lets tail merging share
; a single chain instead, halving the multiplies.

define i64 @symmetric_chains(i64 %a, i64 %b) {
; A510-LABEL: symmetric_chains:
; A510:       // %bb.0: // %entry
; A510-NEXT:    cmp x0, x1
; A510-NEXT:    b.le .LBB2_2
; A510-NEXT:  // %bb.1: // %t
; A510-NEXT:    mov w8, #16963 // =0x4243
; A510-NEXT:    movk w8, #15, lsl #16
; A510-NEXT:    b .LBB2_3
; A510-NEXT:  .LBB2_2: // %f
; A510-NEXT:    mov w8, #33923 // =0x8483
; A510-NEXT:    movk w8, #30, lsl #16
; A510-NEXT:  .LBB2_3: // %join
; A510-NEXT:    add x9, x8, #2
; A510-NEXT:    orr x10, x8, #0x4
; A510-NEXT:    mul x9, x0, x9
; A510-NEXT:    mul x9, x9, x10
; A510-NEXT:    add x10, x8, #6
; A510-NEXT:    mul x9, x9, x10
; A510-NEXT:    orr x10, x8, #0x8
; A510-NEXT:    mul x9, x9, x10
; A510-NEXT:    add x10, x8, #10
; A510-NEXT:    mul x9, x9, x10
; A510-NEXT:    mul x0, x9, x8
; A510-NEXT:    ret
;
; M1-LABEL: symmetric_chains:
; M1:       // %bb.0: // %entry
; M1-NEXT:    mov w8, #33923 // =0x8483
; M1-NEXT:    movk w8, #30, lsl #16
; M1-NEXT:    add x9, x8, #2
; M1-NEXT:    mul x9, x0, x9
; M1-NEXT:    orr x10, x8, #0x4
; M1-NEXT:    mul x9, x9, x10
; M1-NEXT:    add x10, x8, #6
; M1-NEXT:    mul x9, x9, x10
; M1-NEXT:    orr x10, x8, #0x8
; M1-NEXT:    mul x9, x9, x10
; M1-NEXT:    add x10, x8, #10
; M1-NEXT:    mul x9, x9, x10
; M1-NEXT:    mul x8, x9, x8
; M1-NEXT:    mov w9, #16963 // =0x4243
; M1-NEXT:    movk w9, #15, lsl #16
; M1-NEXT:    add x10, x9, #2
; M1-NEXT:    mul x10, x0, x10
; M1-NEXT:    orr x11, x9, #0x4
; M1-NEXT:    mul x10, x10, x11
; M1-NEXT:    add x11, x9, #6
; M1-NEXT:    mul x10, x10, x11
; M1-NEXT:    orr x11, x9, #0x8
; M1-NEXT:    mul x10, x10, x11
; M1-NEXT:    add x11, x9, #10
; M1-NEXT:    mul x10, x10, x11
; M1-NEXT:    mul x9, x10, x9
; M1-NEXT:    cmp x0, x1
; M1-NEXT:    csel x0, x8, x9, le
; M1-NEXT:    ret
entry:
  %c = icmp sgt i64 %a, %b
  br i1 %c, label %t, label %f

t:
  %t0 = mul i64 %a, 1000003
  %t1 = mul i64 %t0, 1000005
  %t2 = mul i64 %t1, 1000007
  %t3 = mul i64 %t2, 1000009
  %t4 = mul i64 %t3, 1000011
  %t5 = mul i64 %t4, 1000013
  br label %join

f:
  %f0 = mul i64 %a, 2000003
  %f1 = mul i64 %f0, 2000005
  %f2 = mul i64 %f1, 2000007
  %f3 = mul i64 %f2, 2000009
  %f4 = mul i64 %f3, 2000011
  %f5 = mul i64 %f4, 2000013
  br label %join

join:
  %p = phi i64 [ %t5, %t ], [ %f5, %f ]
  ret i64 %p
}
