; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mcpu=cortex-a510 -aarch64-enable-atomic-cfg-tidy=0 < %s | FileCheck %s --check-prefixes=CHECK,A510
; RUN: llc -mtriple=aarch64-unknown-linux-gnu -mcpu=neoverse-n1 -aarch64-enable-atomic-cfg-tidy=0 < %s | FileCheck %s --check-prefixes=CHECK,N1

; The two legs compute the same expression, one specialised to a constant
; divisor and one dividing by the runtime value. Their critical paths are
; nearly identical, so the per-PHI critical path check sees almost no
; extension, but merging them makes the specialised leg pay for the sdiv it
; exists to avoid. The branch must survive.

define i64 @div_specialisation(i64 %a, i64 %d) {
entry:
  %c = icmp eq i64 %d, 24000000
  br i1 %c, label %t, label %f

t:
  %q1 = sdiv i64 %a, 24000000
  %m1 = mul i64 %q1, 24000000
  %r1 = sub i64 %a, %m1
  %s1 = mul i64 %q1, 1000000000
  %o1 = add i64 %s1, %r1
  br label %join

f:
  %q2 = sdiv i64 %a, %d
  %m2 = mul i64 %q2, %d
  %r2 = sub i64 %a, %m2
  %s2 = mul i64 %q2, 1000000000
  %o2 = add i64 %s2, %r2
  br label %join

join:
  %p = phi i64 [ %o1, %t ], [ %o2, %f ]
  ret i64 %p
}

; Both legs are a single cheap instruction, so speculating them costs far less
; than a misprediction. This must still be if-converted.

define i64 @cheap_legs(i64 %a, i64 %b, i64 %c) {
entry:
  %cmp = icmp sgt i64 %a, %b
  br i1 %cmp, label %t, label %f

t:
  %x = add i64 %a, %c
  br label %join

f:
  %y = sub i64 %a, %c
  br label %join

join:
  %p = phi i64 [ %x, %t ], [ %y, %f ]
  ret i64 %p
}
