; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -mattr=+neon -verify-machineinstrs < %s | FileCheck %s

; Finding the first set lane of a compare result via cttz of the packed
; bitmask should use a 64-bit scalar view of the mask (SHRN #4 nibble mask
; for 128-bit compares) instead of materializing the packed bitmask.

define i32 @first_match_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: first_match_v16i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    shrn v0.8b, v0.8h, #4
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x8, x8
; CHECK-NEXT:    clz x8, x8
; CHECK-NEXT:    lsr x0, x8, #2
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %cmp = icmp eq <16 x i8> %a, %b
  %mask = bitcast <16 x i1> %cmp to i16
  %ext = zext i16 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 true)
  ret i32 %idx
}

; cttz with defined zero behaviour: an all-zero mask must give 16.
define i16 @first_match_v16i8_zero_defined(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: first_match_v16i8_zero_defined:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    shrn v0.8b, v0.8h, #4
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x8, x8
; CHECK-NEXT:    clz x8, x8
; CHECK-NEXT:    lsr x0, x8, #2
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %cmp = icmp eq <16 x i8> %a, %b
  %mask = bitcast <16 x i1> %cmp to i16
  %idx = call i16 @llvm.cttz.i16(i16 %mask, i1 false)
  ret i16 %idx
}

; A zero-defined cttz of the *extended* mask must not be combined: a zero
; mask would have to produce 32, not 16.
define i32 @first_match_v16i8_zext_zero_defined(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: first_match_v16i8_zext_zero_defined:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, .LCPI2_0
; CHECK-NEXT:    cmeq v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    ldr q1, [x8, :lo12:.LCPI2_0]
; CHECK-NEXT:    and v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-NEXT:    addp v0.16b, v0.16b, v0.16b
; CHECK-NEXT:    umov w8, v0.h[0]
; CHECK-NEXT:    rbit w8, w8
; CHECK-NEXT:    clz w0, w8
; CHECK-NEXT:    ret
  %cmp = icmp eq <16 x i8> %a, %b
  %mask = bitcast <16 x i1> %cmp to i16
  %ext = zext i16 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 false)
  ret i32 %idx
}

define i32 @first_match_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: first_match_v8i16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.8h, v0.8h, v1.8h
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x8, x8
; CHECK-NEXT:    clz x8, x8
; CHECK-NEXT:    lsr x0, x8, #3
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %cmp = icmp eq <8 x i16> %a, %b
  %mask = bitcast <8 x i1> %cmp to i8
  %ext = zext i8 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 true)
  ret i32 %idx
}

define i32 @first_match_v8i8(<8 x i8> %a, <8 x i8> %b) {
; CHECK-LABEL: first_match_v8i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.8b, v0.8b, v1.8b
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x8, x8
; CHECK-NEXT:    clz x8, x8
; CHECK-NEXT:    lsr x0, x8, #3
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %cmp = icmp eq <8 x i8> %a, %b
  %mask = bitcast <8 x i1> %cmp to i8
  %ext = zext i8 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 true)
  ret i32 %idx
}

define i32 @first_match_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: first_match_v4i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    xtn v0.8b, v0.8h
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x8, x8
; CHECK-NEXT:    clz x8, x8
; CHECK-NEXT:    lsr x0, x8, #4
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %cmp = icmp eq <4 x i32> %a, %b
  %mask = bitcast <4 x i1> %cmp to i4
  %ext = zext i4 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 true)
  ret i32 %idx
}

; The guarding mask != 0 test and the cttz should share one scalar view of
; the mask (a single shrn + fmov).
define i32 @first_match_v16i8_guarded(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: first_match_v16i8_guarded:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cmeq v0.16b, v0.16b, v1.16b
; CHECK-NEXT:    shrn v0.8b, v0.8h, #4
; CHECK-NEXT:    fmov x8, d0
; CHECK-NEXT:    rbit x9, x8
; CHECK-NEXT:    cmp x8, #0
; CHECK-NEXT:    clz x9, x9
; CHECK-NEXT:    lsr x9, x9, #2
; CHECK-NEXT:    csinv w0, w9, wzr, ne
; CHECK-NEXT:    ret
  %cmp = icmp eq <16 x i8> %a, %b
  %mask = bitcast <16 x i1> %cmp to i16
  %any = icmp ne i16 %mask, 0
  %ext = zext i16 %mask to i32
  %idx = call i32 @llvm.cttz.i32(i32 %ext, i1 true)
  %res = select i1 %any, i32 %idx, i32 -1
  ret i32 %res
}

declare i16 @llvm.cttz.i16(i16, i1)
declare i32 @llvm.cttz.i32(i32, i1)
