; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; On big-endian targets a bitcast from iN to <N x i1> assigns the most
; significant bit to lane 0, so the bit constants must be reversed.

target datalayout = "E"

define <4 x i1> @unpack_ne_zero_be(i32 %x) {
; CHECK-LABEL: @unpack_ne_zero_be(
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[X:%.*]] to i4
; CHECK-NEXT:    [[CMP:%.*]] = bitcast i4 [[TMP1]] to <4 x i1>
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 8, i32 4, i32 2, i32 1>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: this is the little-endian lane order.

define <4 x i1> @unpack_le_order_be(i32 %x) {
; CHECK-LABEL: @unpack_le_order_be(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x i32> poison, i32 [[X:%.*]], i64 0
; CHECK-NEXT:    [[SPLAT:%.*]] = shufflevector <4 x i32> [[INS]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[AND:%.*]] = and <4 x i32> [[SPLAT]], <i32 1, i32 2, i32 4, i32 8>
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne <4 x i32> [[AND]], zeroinitializer
; CHECK-NEXT:    ret <4 x i1> [[CMP]]
;
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}
