; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

; Tests for canonicalizing the "inverse movemask" idiom that unpacks a scalar
; bit mask into a vector of booleans:
;   icmp ne (and (splat X), <1, 2, 4, ...>), zero
;     --> bitcast (trunc X) to <N x i1>

define <8 x i1> @unpack_ne_zero(i32 %x) {
  %ins = insertelement <8 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %cmp = icmp ne <8 x i32> %and, zeroinitializer
  ret <8 x i1> %cmp
}

; Comparing eq zero gives the inverted mask.

define <8 x i1> @unpack_eq_zero(i32 %x) {
  %ins = insertelement <8 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %cmp = icmp eq <8 x i32> %and, zeroinitializer
  ret <8 x i1> %cmp
}

; Comparing eq against the bit constants themselves is equivalent to ne zero.

define <8 x i1> @unpack_eq_bits(i32 %x) {
  %ins = insertelement <8 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %cmp = icmp eq <8 x i32> %and, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  ret <8 x i1> %cmp
}

define <8 x i1> @unpack_ne_bits(i32 %x) {
  %ins = insertelement <8 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %cmp = icmp ne <8 x i32> %and, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  ret <8 x i1> %cmp
}

; Fewer lanes than scalar bits: only the low 4 bits are unpacked.

define <4 x i1> @unpack_narrow(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Lane count == element width: the trunc is a no-op.

define <8 x i1> @unpack_i8_full(i8 %x) {
  %ins = insertelement <8 x i8> poison, i8 %x, i64 0
  %splat = shufflevector <8 x i8> %ins, <8 x i8> poison, <8 x i32> zeroinitializer
  %and = and <8 x i8> %splat, <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 128>
  %cmp = icmp ne <8 x i8> %and, zeroinitializer
  ret <8 x i1> %cmp
}

; The motivating case: a mask that is packed into an integer ("movemask") and
; immediately unpacked again must cancel and stay in vector form.

define <8 x float> @pack_unpack_roundtrip(<8 x i32> %a, <8 x float> %x, <8 x float> %y) {
  %mask = icmp slt <8 x i32> %a, zeroinitializer
  %pack = bitcast <8 x i1> %mask to i8
  %bits = zext i8 %pack to i32
  %ins = insertelement <8 x i32> poison, i32 %bits, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %unpack = icmp ne <8 x i32> %and, zeroinitializer
  %sel = select <8 x i1> %unpack, <8 x float> %x, <8 x float> %y
  ret <8 x float> %sel
}

; Same, with the inverted compare feeding the select.

define <8 x float> @pack_unpack_roundtrip_inverted(<8 x i32> %a, <8 x float> %x, <8 x float> %y) {
  %mask = icmp slt <8 x i32> %a, zeroinitializer
  %pack = bitcast <8 x i1> %mask to i8
  %bits = zext i8 %pack to i32
  %ins = insertelement <8 x i32> poison, i32 %bits, i64 0
  %splat = shufflevector <8 x i32> %ins, <8 x i32> poison, <8 x i32> zeroinitializer
  %and = and <8 x i32> %splat, <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>
  %unpack = icmp eq <8 x i32> %and, zeroinitializer
  %sel = select <8 x i1> %unpack, <8 x float> %y, <8 x float> %x
  ret <8 x float> %sel
}

; Negative test: not a sequence of one-bit values.

define <4 x i1> @unpack_not_pow2(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 12>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: powers of 2, but lane I does not test bit I.

define <4 x i1> @unpack_shifted_bits(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 2, i32 4, i32 8, i32 16>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: poison lane in the bit constants.

define <4 x i1> @unpack_poison_lane(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 poison, i32 8>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: non-equality predicate.

define <4 x i1> @unpack_wrong_pred(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  %cmp = icmp ult <4 x i32> %and, <i32 1, i32 2, i32 4, i32 8>
  ret <4 x i1> %cmp
}

; Negative test: the 'and' has another use.

declare void @use(<4 x i32>)

define <4 x i1> @unpack_and_extra_use(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  call void @use(<4 x i32> %and)
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: the splat has another use.

define <4 x i1> @unpack_splat_extra_use(i32 %x) {
  %ins = insertelement <4 x i32> poison, i32 %x, i64 0
  %splat = shufflevector <4 x i32> %ins, <4 x i32> poison, <4 x i32> zeroinitializer
  call void @use(<4 x i32> %splat)
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}

; Negative test: not a splat (mismatched shuffle index).

define <4 x i1> @unpack_not_splat(<4 x i32> %v) {
  %splat = shufflevector <4 x i32> %v, <4 x i32> poison, <4 x i32> <i32 0, i32 0, i32 1, i32 0>
  %and = and <4 x i32> %splat, <i32 1, i32 2, i32 4, i32 8>
  %cmp = icmp ne <4 x i32> %and, zeroinitializer
  ret <4 x i1> %cmp
}
