; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s --check-prefixes=CHECK,LE
; RUN: opt -S -passes=instcombine -data-layout=E < %s | FileCheck %s --check-prefixes=CHECK,BE

; Reductions over per-lane bit-position weights of a bool mask are a
; compare->bitmask ("movemask") bit-pack: lane i of the mask becomes bit i of
; the scalar result. Fold them to `zext(bitcast <N x i1> to iN)`. The lane->bit
; mapping of the bitcast only holds on little-endian targets, so the fold is
; suppressed for big-endian data layouts.

declare void @use(<8 x i8>)

; select %m, <1,2,4,...,128>, zeroinitializer  ->  bitcast to i8
define i8 @select_form_i8(<8 x i1> %m) {
; LE-LABEL: @select_form_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @select_form_i8(
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Wider element type: bitcast to i8, then zext to i32.
define i32 @select_form_i32(<8 x i1> %m) {
; LE-LABEL: @select_form_i32(
; LE-NEXT:    [[TMP1:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    [[R:%.*]] = zext i8 [[TMP1]] to i32
; LE-NEXT:    ret i32 [[R]]
;
; BE-LABEL: @select_form_i32(
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i32> <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>, <8 x i32> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i32 @llvm.vector.reduce.or.v8i32(<8 x i32> [[SEL]])
; BE-NEXT:    ret i32 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i32> <i32 1, i32 2, i32 4, i32 8, i32 16, i32 32, i32 64, i32 128>, <8 x i32> zeroinitializer
  %r = call i32 @llvm.vector.reduce.or.v8i32(<8 x i32> %sel)
  ret i32 %r
}

; shl (zext %m), <0,1,2,...,7> -- the shape the SLP vectorizer emits.
define i8 @shl_form_i8(<8 x i1> %m) {
; LE-LABEL: @shl_form_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @shl_form_i8(
; BE-NEXT:    [[SHL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SHL]])
; BE-NEXT:    ret i8 [[R]]
;
  %z = zext <8 x i1> %m to <8 x i8>
  %shl = shl <8 x i8> %z, <i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %shl)
  ret i8 %r
}

; and (sext %m), <1,2,4,...,128>
define i8 @and_form_i8(<8 x i1> %m) {
; LE-LABEL: @and_form_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @and_form_i8(
; BE-NEXT:    [[AND:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[AND]])
; BE-NEXT:    ret i8 [[R]]
;
  %s = sext <8 x i1> %m to <8 x i8>
  %and = and <8 x i8> %s, <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %and)
  ret i8 %r
}

; mul (zext %m), <1,2,4,...,128>
define i8 @mul_form_i8(<8 x i1> %m) {
; LE-LABEL: @mul_form_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @mul_form_i8(
; BE-NEXT:    [[MUL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[MUL]])
; BE-NEXT:    ret i8 [[R]]
;
  %z = zext <8 x i1> %m to <8 x i8>
  %mul = mul <8 x i8> %z, <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %mul)
  ret i8 %r
}

; reduce.add is equivalent because the lane contributions are disjoint bits.
define i8 @add_reduce_i8(<8 x i1> %m) {
; LE-LABEL: @add_reduce_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @add_reduce_i8(
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.add.v8i8(<8 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.add.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; reduce.xor is likewise equivalent.
define i8 @xor_reduce_i8(<8 x i1> %m) {
; LE-LABEL: @xor_reduce_i8(
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M:%.*]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @xor_reduce_i8(
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.xor.v8i8(<8 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.xor.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; A 4-lane mask packs into an i4.
define i8 @select_form_n4(<4 x i1> %m) {
; LE-LABEL: @select_form_n4(
; LE-NEXT:    [[TMP1:%.*]] = bitcast <4 x i1> [[M:%.*]] to i4
; LE-NEXT:    [[R:%.*]] = zext i4 [[TMP1]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @select_form_n4(
; BE-NEXT:    [[SEL:%.*]] = select <4 x i1> [[M:%.*]], <4 x i8> <i8 1, i8 2, i8 4, i8 8>, <4 x i8> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v4i8(<4 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %sel = select <4 x i1> %m, <4 x i8> <i8 1, i8 2, i8 4, i8 8>, <4 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v4i8(<4 x i8> %sel)
  ret i8 %r
}

; The 64-lane u8-packing case from the motivating workload (#121691).
define i64 @select_form_i64_n64(<64 x i1> %m) {
; LE-LABEL: @select_form_i64_n64(
; LE-NEXT:    [[R:%.*]] = bitcast <64 x i1> [[M:%.*]] to i64
; LE-NEXT:    ret i64 [[R]]
;
; BE-LABEL: @select_form_i64_n64(
; BE-NEXT:    [[SEL:%.*]] = select <64 x i1> [[M:%.*]], <64 x i64> <i64 1, i64 2, i64 4, i64 8, i64 16, i64 32, i64 64, i64 128, i64 256, i64 512, i64 1024, i64 2048, i64 4096, i64 8192, i64 16384, i64 32768, i64 65536, i64 131072, i64 262144, i64 524288, i64 1048576, i64 2097152, i64 4194304, i64 8388608, i64 16777216, i64 33554432, i64 67108864, i64 134217728, i64 268435456, i64 536870912, i64 1073741824, i64 2147483648, i64 4294967296, i64 8589934592, i64 17179869184, i64 34359738368, i64 68719476736, i64 137438953472, i64 274877906944, i64 549755813888, i64 1099511627776, i64 2199023255552, i64 4398046511104, i64 8796093022208, i64 17592186044416, i64 35184372088832, i64 70368744177664, i64 140737488355328, i64 281474976710656, i64 562949953421312, i64 1125899906842624, i64 2251799813685248, i64 4503599627370496, i64 9007199254740992, i64 18014398509481984, i64 36028797018963968, i64 72057594037927936, i64 144115188075855872, i64 288230376151711744, i64 576460752303423488, i64 1152921504606846976, i64 2305843009213693952, i64 4611686018427387904, i64 -9223372036854775808>, <64 x i64> zeroinitializer
; BE-NEXT:    [[R:%.*]] = call i64 @llvm.vector.reduce.or.v64i64(<64 x i64> [[SEL]])
; BE-NEXT:    ret i64 [[R]]
;
  %sel = select <64 x i1> %m, <64 x i64> <i64 1, i64 2, i64 4, i64 8, i64 16, i64 32, i64 64, i64 128, i64 256, i64 512, i64 1024, i64 2048, i64 4096, i64 8192, i64 16384, i64 32768, i64 65536, i64 131072, i64 262144, i64 524288, i64 1048576, i64 2097152, i64 4194304, i64 8388608, i64 16777216, i64 33554432, i64 67108864, i64 134217728, i64 268435456, i64 536870912, i64 1073741824, i64 2147483648, i64 4294967296, i64 8589934592, i64 17179869184, i64 34359738368, i64 68719476736, i64 137438953472, i64 274877906944, i64 549755813888, i64 1099511627776, i64 2199023255552, i64 4398046511104, i64 8796093022208, i64 17592186044416, i64 35184372088832, i64 70368744177664, i64 140737488355328, i64 281474976710656, i64 562949953421312, i64 1125899906842624, i64 2251799813685248, i64 4503599627370496, i64 9007199254740992, i64 18014398509481984, i64 36028797018963968, i64 72057594037927936, i64 144115188075855872, i64 288230376151711744, i64 576460752303423488, i64 1152921504606846976, i64 2305843009213693952, i64 4611686018427387904, i64 -9223372036854775808>, <64 x i64> zeroinitializer
  %r = call i64 @llvm.vector.reduce.or.v64i64(<64 x i64> %sel)
  ret i64 %r
}

; Negative: weights are not the 1<<i ramp.
define i8 @not_power_of_two(<8 x i1> %m) {
; CHECK-LABEL: @not_power_of_two(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 65>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 65>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Negative: reversed bit weights (lane i owns bit N-1-i) would need a
; bitreverse, not a plain bitcast.
define i8 @reversed_weights(<8 x i1> %m) {
; CHECK-LABEL: @reversed_weights(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 -128, i8 64, i8 32, i8 16, i8 8, i8 4, i8 2, i8 1>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 -128, i8 64, i8 32, i8 16, i8 8, i8 4, i8 2, i8 1>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Negative: non-zero false arm.
define i8 @nonzero_false_arm(<8 x i1> %m) {
; CHECK-LABEL: @nonzero_false_arm(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> splat (i8 1)
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> splat (i8 1)
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Negative: reduce.and is not an OR of disjoint bits.
define i8 @and_reduce(<8 x i1> %m) {
; CHECK-LABEL: @and_reduce(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.and.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.and.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Negative: the weighted vector has another use, so it would not die.
define i8 @multi_use(<8 x i1> %m) {
; CHECK-LABEL: @multi_use(
; CHECK-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
; CHECK-NEXT:    call void @use(<8 x i8> [[SEL]])
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  call void @use(<8 x i8> %sel)
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; Negative: more lanes than element bits -- bit N-1 does not fit a lane.
define i8 @too_many_lanes(<16 x i1> %m) {
; CHECK-LABEL: @too_many_lanes(
; CHECK-NEXT:    [[SHL:%.*]] = select <16 x i1> [[M:%.*]], <16 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128, i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <16 x i8> zeroinitializer
; CHECK-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> [[SHL]])
; CHECK-NEXT:    ret i8 [[R]]
;
  %z = zext <16 x i1> %m to <16 x i8>
  %shl = shl <16 x i8> %z, <i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7, i8 0, i8 1, i8 2, i8 3, i8 4, i8 5, i8 6, i8 7>
  %r = call i8 @llvm.vector.reduce.or.v16i8(<16 x i8> %shl)
  ret i8 %r
}

; Inverted select arms (weights in the false arm): the shape InstCombine's own
; icmp eq/ne canonicalization produces for compare-fed masks.
define i8 @inverted_select_form_i8(<8 x i1> %m) {
; LE-LABEL: @inverted_select_form_i8(
; LE-NEXT:    [[TMP1:%.*]] = xor <8 x i1> [[M:%.*]], splat (i1 true)
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @inverted_select_form_i8(
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M:%.*]], <8 x i8> zeroinitializer, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %sel = select <8 x i1> %m, <8 x i8> zeroinitializer, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

; A compare-fed mask: instcombine canonicalizes the icmp ne to icmp eq and
; swaps the select arms before the reduction is visited.
define i8 @cmp_fed_mask_i8(<8 x i8> %v) {
; LE-LABEL: @cmp_fed_mask_i8(
; LE-NEXT:    [[M_NOT:%.*]] = icmp ne <8 x i8> [[V:%.*]], zeroinitializer
; LE-NEXT:    [[R:%.*]] = bitcast <8 x i1> [[M_NOT]] to i8
; LE-NEXT:    ret i8 [[R]]
;
; BE-LABEL: @cmp_fed_mask_i8(
; BE-NEXT:    [[M_NOT:%.*]] = icmp eq <8 x i8> [[V:%.*]], zeroinitializer
; BE-NEXT:    [[SEL:%.*]] = select <8 x i1> [[M_NOT]], <8 x i8> zeroinitializer, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>
; BE-NEXT:    [[R:%.*]] = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> [[SEL]])
; BE-NEXT:    ret i8 [[R]]
;
  %m = icmp ne <8 x i8> %v, zeroinitializer
  %sel = select <8 x i1> %m, <8 x i8> <i8 1, i8 2, i8 4, i8 8, i8 16, i8 32, i8 64, i8 -128>, <8 x i8> zeroinitializer
  %r = call i8 @llvm.vector.reduce.or.v8i8(<8 x i8> %sel)
  ret i8 %r
}

