; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx512f,+avx512bw,+avx512vl | FileCheck %s

; AVX512 masks bitwise logic ops at 32/64-bit granularity only, so folding
; "binop X, (vselect C, Y, Identity)" into a masked op cannot be contracted for
; i8/i16 elements - it needs a separate merge-move, which puts a second
; instruction on X's dependency chain. Check we keep the unfolded form there,
; and still fold for i32 where a single masked op is available.

define <16 x i16> @or_v16i16(<16 x i16> %acc, <16 x i16> %a, <16 x i16> %rhs, <16 x i16> %y) {
; CHECK-LABEL: or_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpcmpltuw %ymm2, %ymm1, %k1
; CHECK-NEXT:    vmovdqu16 %ymm3, %ymm1 {%k1} {z}
; CHECK-NEXT:    vpor %ymm1, %ymm0, %ymm0
; CHECK-NEXT:    retq
  %c = icmp ult <16 x i16> %a, %rhs
  %s = select <16 x i1> %c, <16 x i16> %y, <16 x i16> zeroinitializer
  %o = or <16 x i16> %acc, %s
  ret <16 x i16> %o
}

define <32 x i8> @xor_v32i8(<32 x i8> %acc, <32 x i8> %a, <32 x i8> %rhs, <32 x i8> %y) {
; CHECK-LABEL: xor_v32i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpcmpltub %ymm2, %ymm1, %k1
; CHECK-NEXT:    vmovdqu8 %ymm3, %ymm1 {%k1} {z}
; CHECK-NEXT:    vpxor %ymm1, %ymm0, %ymm0
; CHECK-NEXT:    retq
  %c = icmp ult <32 x i8> %a, %rhs
  %s = select <32 x i1> %c, <32 x i8> %y, <32 x i8> zeroinitializer
  %o = xor <32 x i8> %acc, %s
  ret <32 x i8> %o
}

define <8 x i32> @or_v8i32(<8 x i32> %acc, <8 x i32> %a, <8 x i32> %rhs, <8 x i32> %y) {
; CHECK-LABEL: or_v8i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpcmpltud %ymm2, %ymm1, %k1
; CHECK-NEXT:    vpord %ymm3, %ymm0, %ymm0 {%k1}
; CHECK-NEXT:    retq
  %c = icmp ult <8 x i32> %a, %rhs
  %s = select <8 x i1> %c, <8 x i32> %y, <8 x i32> zeroinitializer
  %o = or <8 x i32> %acc, %s
  ret <8 x i32> %o
}

; add has masked forms at every element width, so the fold still applies.
define <16 x i16> @add_v16i16(<16 x i16> %acc, <16 x i16> %a, <16 x i16> %rhs, <16 x i16> %y) {
; CHECK-LABEL: add_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpcmpltuw %ymm2, %ymm1, %k1
; CHECK-NEXT:    vpaddw %ymm3, %ymm0, %ymm0 {%k1}
; CHECK-NEXT:    retq
  %c = icmp ult <16 x i16> %a, %rhs
  %s = select <16 x i1> %c, <16 x i16> %y, <16 x i16> zeroinitializer
  %o = add <16 x i16> %acc, %s
  ret <16 x i16> %o
}

define <16 x i16> @and_v16i16(<16 x i16> %acc, <16 x i16> %a, <16 x i16> %rhs, <16 x i16> %y) {
; CHECK-LABEL: and_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpcmpltuw %ymm2, %ymm1, %k1
; CHECK-NEXT:    vpcmpeqd %ymm1, %ymm1, %ymm1
; CHECK-NEXT:    vmovdqu16 %ymm3, %ymm1 {%k1}
; CHECK-NEXT:    vpand %ymm1, %ymm0, %ymm0
; CHECK-NEXT:    retq
  %c = icmp ult <16 x i16> %a, %rhs
  %s = select <16 x i1> %c, <16 x i16> %y, <16 x i16> splat(i16 -1)
  %o = and <16 x i16> %acc, %s
  ret <16 x i16> %o
}
