; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes='loop(loop-idiom)' -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Positional bit-pack: 64 unsigned compares packed into an i64 bitmask.
define i64 @bitpack_ugt_64(ptr %base, i32 %k) {
; CHECK-LABEL: @bitpack_ugt_64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <64 x i32>, ptr [[BASE:%.*]], align 4
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <64 x i32> poison, i32 [[K:%.*]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <64 x i32> [[DOTSPLATINSERT]], <64 x i32> poison, <64 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ugt <64 x i32> [[TMP0]], [[DOTSPLAT]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <64 x i1> [[TMP1]] to i64
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret i64 [[TMP2]]
;
entry:
  br label %loop
loop:
  %acc = phi i64 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %p = getelementptr inbounds i32, ptr %base, i64 %j
  %v = load i32, ptr %p, align 4
  %c = icmp ugt i32 %v, %k
  %z = zext i1 %c to i64
  %s = shl i64 %z, %j
  %or = or i64 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 64
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i64 [ %or, %loop ]
  ret i64 %r
}

; Same shape, 8 lanes into an i8.
define i8 @bitpack_slt_8(ptr %base, i32 %k) {
; CHECK-LABEL: @bitpack_slt_8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i32>, ptr [[BASE:%.*]], align 4
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <8 x i32> poison, i32 [[K:%.*]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <8 x i32> [[DOTSPLATINSERT]], <8 x i32> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt <8 x i32> [[TMP0]], [[DOTSPLAT]]
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i1> [[TMP1]] to i8
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    ret i8 [[TMP2]]
;
entry:
  br label %loop
loop:
  %acc = phi i8 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %p = getelementptr inbounds i32, ptr %base, i64 %j
  %v = load i32, ptr %p, align 4
  %c = icmp slt i32 %v, %k
  %z = zext i1 %c to i8
  %j.trunc = trunc i64 %j to i8
  %s = shl i8 %z, %j.trunc
  %or = or i8 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 8
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i8 [ %or, %loop ]
  ret i8 %r
}

; Negative: non-power-of-two trip count has no legal mask type.
define i64 @negative_trip_count_7(ptr %base, i32 %k) {
; CHECK-LABEL: @negative_trip_count_7(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[OR:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[J_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[BASE:%.*]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[V]], [[K:%.*]]
; CHECK-NEXT:    [[Z:%.*]] = zext i1 [[C]] to i64
; CHECK-NEXT:    [[S:%.*]] = shl i64 [[Z]], [[J]]
; CHECK-NEXT:    [[OR]] = or i64 [[S]], [[ACC]]
; CHECK-NEXT:    [[J_NEXT]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[J_NEXT]], 7
; CHECK-NEXT:    br i1 [[EC]], label [[EXIT:%.*]], label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[OR]], [[LOOP]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  br label %loop
loop:
  %acc = phi i64 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %p = getelementptr inbounds i32, ptr %base, i64 %j
  %v = load i32, ptr %p, align 4
  %c = icmp ugt i32 %v, %k
  %z = zext i1 %c to i64
  %s = shl i64 %z, %j
  %or = or i64 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 7
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i64 [ %or, %loop ]
  ret i64 %r
}

; Negative: stride 2 is not a consecutive lane walk.
define i64 @negative_stride2(ptr %base, i32 %k) {
; CHECK-LABEL: @negative_stride2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[OR:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[J_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[IDX:%.*]] = shl nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[BASE:%.*]], i64 [[IDX]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[V]], [[K:%.*]]
; CHECK-NEXT:    [[Z:%.*]] = zext i1 [[C]] to i64
; CHECK-NEXT:    [[S:%.*]] = shl i64 [[Z]], [[J]]
; CHECK-NEXT:    [[OR]] = or i64 [[S]], [[ACC]]
; CHECK-NEXT:    [[J_NEXT]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[J_NEXT]], 64
; CHECK-NEXT:    br i1 [[EC]], label [[EXIT:%.*]], label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[OR]], [[LOOP]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  br label %loop
loop:
  %acc = phi i64 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %idx = shl nuw nsw i64 %j, 1
  %p = getelementptr inbounds i32, ptr %base, i64 %idx
  %v = load i32, ptr %p, align 4
  %c = icmp ugt i32 %v, %k
  %z = zext i1 %c to i64
  %s = shl i64 %z, %j
  %or = or i64 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 64
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i64 [ %or, %loop ]
  ret i64 %r
}

; Negative: the bit position is not the induction variable (reversed).
define i64 @negative_reversed_bits(ptr %base, i32 %k) {
; CHECK-LABEL: @negative_reversed_bits(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[OR:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[J_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[BASE:%.*]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[V]], [[K:%.*]]
; CHECK-NEXT:    [[Z:%.*]] = zext i1 [[C]] to i64
; CHECK-NEXT:    [[REV:%.*]] = sub i64 63, [[J]]
; CHECK-NEXT:    [[S:%.*]] = shl i64 [[Z]], [[REV]]
; CHECK-NEXT:    [[OR]] = or i64 [[S]], [[ACC]]
; CHECK-NEXT:    [[J_NEXT]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[J_NEXT]], 64
; CHECK-NEXT:    br i1 [[EC]], label [[EXIT:%.*]], label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[OR]], [[LOOP]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  br label %loop
loop:
  %acc = phi i64 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %p = getelementptr inbounds i32, ptr %base, i64 %j
  %v = load i32, ptr %p, align 4
  %c = icmp ugt i32 %v, %k
  %z = zext i1 %c to i64
  %rev = sub i64 63, %j
  %s = shl i64 %z, %rev
  %or = or i64 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 64
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i64 [ %or, %loop ]
  ret i64 %r
}

; Negative: an extra store in the loop body must not be dropped.
define i64 @negative_extra_store(ptr %base, i32 %k, ptr %sink) {
; CHECK-LABEL: @negative_extra_store(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[ACC:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[OR:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[J_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[P:%.*]] = getelementptr inbounds i32, ptr [[BASE:%.*]], i64 [[J]]
; CHECK-NEXT:    [[V:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    store i32 [[V]], ptr [[SINK:%.*]], align 4
; CHECK-NEXT:    [[C:%.*]] = icmp ugt i32 [[V]], [[K:%.*]]
; CHECK-NEXT:    [[Z:%.*]] = zext i1 [[C]] to i64
; CHECK-NEXT:    [[S:%.*]] = shl i64 [[Z]], [[J]]
; CHECK-NEXT:    [[OR]] = or i64 [[S]], [[ACC]]
; CHECK-NEXT:    [[J_NEXT]] = add nuw nsw i64 [[J]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp eq i64 [[J_NEXT]], 64
; CHECK-NEXT:    br i1 [[EC]], label [[EXIT:%.*]], label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    [[R:%.*]] = phi i64 [ [[OR]], [[LOOP]] ]
; CHECK-NEXT:    ret i64 [[R]]
;
entry:
  br label %loop
loop:
  %acc = phi i64 [ 0, %entry ], [ %or, %loop ]
  %j = phi i64 [ 0, %entry ], [ %j.next, %loop ]
  %p = getelementptr inbounds i32, ptr %base, i64 %j
  %v = load i32, ptr %p, align 4
  store i32 %v, ptr %sink, align 4
  %c = icmp ugt i32 %v, %k
  %z = zext i1 %c to i64
  %s = shl i64 %z, %j
  %or = or i64 %s, %acc
  %j.next = add nuw nsw i64 %j, 1
  %ec = icmp eq i64 %j.next, 64
  br i1 %ec, label %exit, label %loop
exit:
  %r = phi i64 [ %or, %loop ]
  ret i64 %r
}
